Repository resteasy/resteasy, pull requests merged in 2018-04, with the labels that each got.

#1477 [RESTEASY-1858] Run intergration tests by default with Wildfly 12.0.0…
  jboss-modules/src/main/resources/modules/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/main/module.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForWildFly101.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
  testsuite/pom.xml
Labels: 3.5

#1476 [RESTEASY-1858] Run intergration tests by default with Wildfly 12.0.0…
  jboss-modules/src/main/resources/modules/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/main/module.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForWildFly101.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
  testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/asynch/ComprehensiveJaxrsTest.java
  testsuite/pom.xml
Labels: master

#1475 [WFLY-10158] Upgrade Yasson to 1.0.1
  resteasy-dependencies-bom/pom.xml
Labels: master

#1482 RESTEASY-1842
  docbook/pom.xml
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/Multipart.xml
Labels: master

#1484 [RESTEASY-1823] Patch response codes not found, bad request, conflict…
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/BadRequestException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
Labels: master

#1485 Less verbose logging
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/i18n/Messages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ReaderException.java
Labels: master

#1486 [RESTEASY-1827] Fix org.glassfish:javax.json dependency scope
  providers/json-binding/pom.xml
Labels: master

#1487 [RESTEASY-1822]:Accept-patch header is missing in the response for th…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/HttpHeaderNames.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/JAXRS21PatchTest.java
Labels: master

#1490 [RESTEASY-1833]:Add option to allow always reconnect even if EventSin…
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#1489 Upgrade Jackson2 to 2.9.5 and reactivestreams api to 1.0.2 to sync wi…
  resteasy-dependencies-bom/pom.xml
Labels: master

#1491 [RESTEASY-1805] (#1449)
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/LocatorRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/POJOResourceFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/SingletonResource.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceClass.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceConstructor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceLocator.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceMethod.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/MethodParameter.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClass.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClassProcessor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceConstructor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceLocator.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceMethod.java
  resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRegistry.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxResteasyDeployment.java
Labels: 3.6

#1495 [RESTEASY-1862] JettyClientEngine
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  resteasy-client/pom.xml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyClientEngine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyContentStream.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/JettyResponseStream.java
  resteasy-dependencies-bom/pom.xml
  testsuite/arquillian-utils/pom.xml
  testsuite/unit-tests/pom.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/JettyClientEngineTest.java
Labels: master
