Repository resteasy/resteasy, pull requests merged in 2018-06, with the labels that each got.

#1533 [RESTEASY-1346 / RESTEASY-1418] RESTEasy Tracing Feature | Part 1
  resteasy-bom/pom.xml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClient.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/SingletonResource.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ListenerBootstrap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyServerTracingEvent.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingConfig.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingEvent.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingInfo.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLevel.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLogger.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLoggerImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingMessage.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingUtils.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/BasicTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/HttpMethodOverride.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/OnDemandTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingApp.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingConfigResource.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/tracing/logging.properties
Labels: master

#1542 [RESTEASY-1805] Documentation
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/Resources_Metadata.xml
Labels: master

#1538 Async filter exception bug
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/UndertowTestRunner.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/ExceptionThrowingFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/FilterException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResourceImpl.java
Labels: master

#1546 Making the ResponseStreamPrematurelyClosedTest test more verbose in c…
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseStreamPrematurelyClosedTest.java
Labels: master

#1547 Print more logs
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseStreamPrematurelyClosedTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/TestResourceImpl.java
Labels: Do Not Merge, master

#1531 [RESTEASY-1798]
  docbook/reference/en/en-US/modules/Reactive.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/annotations/Stream.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawFlowableRxJava2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava1Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawByteArrayMessageBodyReaderWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawFlowableRxJava2Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawMediaTypes.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawObservableRxJava1Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawObservableRxJava2Resource.java
Labels: master

#1553 [RESTEASY-1919] Getting rid of jaxrs20 modules and @Jaxrs21 annotation
  pom.xml
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  resteasy-client/jaxrs20/pom.xml
  resteasy-client/pom.xml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AsynchronousInvoke.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilderInterface.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/CompletionStageRxInvokerImpl.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/CompletionStageRxInvokerProvider.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/FormProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/InvocationProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/AbstractInvocationCollectionProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/CookieParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/FormParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/MessageBodyParameterProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/URIParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  resteasy-client/src/main/jaxrs20/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  resteasy-client/src/main/jaxrs20/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
  resteasy-client/src/main/jaxrs20/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
  resteasy-dependencies-bom/pom.xml
  resteasy-jaxrs/jaxrs20/pom.xml
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/FindAnnotation.java
  resteasy-jaxrs/src/main/resources-jaxrs20/META-INF/services/javax.ws.rs.ext.Providers
  resteasy-jaxrs/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/Jaxrs21.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/JAXRS21PatchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/CustomJackson2ProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonp/JsonpTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseCORSFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEnablingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkClosingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SsePostResourceMethodInvokerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseSmokeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/AnotherPublisherResponseTest.java
  testsuite/pom.xml
Labels: 3.6

#1555 [RESTEASY-1783] Removing deprecated YamlProvider
  as8-resteasy/assembly.xml
  distribution/assembly.xml
  distribution/pom.xml
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/I18N.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  docbook/reference/en/en-US/modules/Yaml.xml
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-yaml-provider/main/module.xml
  profiling-tests/pom.xml
  providers/pom.xml
  providers/yaml/pom.xml
  providers/yaml/src/main/java/org/jboss/resteasy/plugins/providers/YamlProvider.java
  providers/yaml/src/main/java/org/jboss/resteasy/plugins/providers/yaml/i18n/LogMessages.java
  providers/yaml/src/main/java/org/jboss/resteasy/plugins/providers/yaml/i18n/Messages.java
  providers/yaml/src/test/java/org/jboss/resteasy/test/i18n/I18nTestMessages_en.java
  providers/yaml/src/test/java/org/jboss/resteasy/test/i18n/I18nTestMessages_xx.java
  providers/yaml/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  providers/yaml/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
  providers/yaml/src/test/resources/i18n/Messages.i18n_en.properties
  providers/yaml/src/test/resources/i18n/Messages.i18n_xx.properties
  resteasy-bom/pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/README.MD
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlPojoBindingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/YamlProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlPojoBindingNestedObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlPojoBindingObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlProviderNestedObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlProviderObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlProviderResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/yaml/resource/YamlResource.java
  testsuite/integration-tests/src/test/resources/META-INF/services/javax.ws.rs.ext.Providers
  testsuite/legacy-integration-tests/pom.xml
Labels: master

#1557 [RESTEASY-1798]
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/AsyncClientResponseProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableNoStreamResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableResourceNoStreamImpl.java
Labels: 3.6

#1558 [RESTEASY-1798]
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/AsyncClientResponseProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableNoStreamResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableResourceNoStreamImpl.java
Labels: master

#1562 [RESTEASY-1798] Set a dependency to resteasy-rxjava2 instead of embed…
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseRawStreamTest.java
Labels: master

#1543 [RESTEASY-1927] ClientResponseContextImpl: getEntityStream returns possibly exhausted inputStream
  resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
  resteasy-client-jetty/src/test/java/org/jboss/resteasy/test/client/jetty/JettyClientEngineTest.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponseContextImpl.java
Labels: master

#1568 [RESTEASY-1879] Move MP REST Client 1.0 impl to separate module (take II)
  jboss-modules/build.xml
  jboss-modules/pom.xml
  pom.xml
  resteasy-cdi/pom.xml
  resteasy-cdi/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  resteasy-client-microprofile/pom.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientExtension.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/DefaultResponseExceptionMapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocation.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocationBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvoker.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientWebTarget.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClient.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyProviderFactory.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilderResolver.java
  resteasy-client-microprofile/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  resteasy-client-microprofile/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClient.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyWebTarget.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvokerFactory.java
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/integration-tests/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: master

#1571 [RESTEASY-1879] Move MP REST Client 1.0 impl to separate module
  jboss-modules/build.xml
  jboss-modules/pom.xml
  pom.xml
  resteasy-cdi/pom.xml
  resteasy-cdi/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  resteasy-client-microprofile/pom.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientExtension.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/DefaultResponseExceptionMapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocation.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocationBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientWebTarget.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClient.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyProviderFactory.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilderResolver.java
  resteasy-client-microprofile/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  resteasy-client-microprofile/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClient.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyWebTarget.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocationBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/integration-tests/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: 3.6

#1576 [RESTEASY-1798] Removing resteasy-rxjava jboss module and fixing inte…
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-rxjava/main/module.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilRxJava.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/NoStreamRxTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableSSECompatibilityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava1Test.java
  testsuite/pom.xml
Labels: master

#1579 Fix test on container with jsonb always on
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
  testsuite/integration-tests/src/test/resources/jboss-deployment-structure-no-json-b.xml
Labels: 3.6

#1580 [RESTEASY-1920][RESTEASY-1911] Exclude tests failing on WFLY 13
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly13.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/JacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/ProxyWithGenericReturnTypeJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJaxbCoexistenceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ProxyWithGenericReturnTypeJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/pom.xml
Labels: 3.6

#1583 [RESTEASY-1933] Excluding tests
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
Labels: 3.6

#1585 [RESTEASY-1935] Excluding part of the test
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/PriorityExecutionTest.java
Labels: 3.6

#1584 [RESTEASY-1798] Unify test deployment dependencies
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/RxCompletionStageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/resource/RxCompletionStageResourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/NoStreamRxTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableSSECompatibilityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/NoStreamRx2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2FlowableProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2FlowableSSECompatibilityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2FlowableTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2ObservableProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2ObservableSSECompatibilityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2ObservableTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2SingleClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2SingleProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2SingleProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2SingleServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava2/Rx2SingleTest.java
Labels: master

#1573 [RESTEASY-1861] RESTEasy ignores @ConstrainedTo in some situations
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/CustomConstrainedFeatureTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomClientConstrainedFeature.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomConstrainedFeatureResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/CustomServerConstrainedFeature.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/custom/CustomConstrainedFeature.Providers
Labels: master

#1587 [RESTEASY-1932]
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java
Labels: master

#1588 [RESTEASY-1932]
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java
Labels: 3.0

#1537 [JBEAP-13198][RESTEASY-1712] added check and warning msg for ambiguou…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/Registry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRegistry.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/TestResource1.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/TestResource2.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/TestSubResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/resource/SubResourceWarningResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/resource/TestResource1.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/resource/TestResource2.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/resource/TestSubResource.java
Labels: 3.0

#1535 [RESTEASY-1838]: Remove the SseEventSource.open() 30 seconds timeout to be fully synch
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
Labels: master

#1590 [RESTEASY-1936] Testsuite elytron module misconfiguration
  testsuite/pom.xml
Labels: 3.6

#1591 [RESTEASY-1936] Testsuite elytron module misconfiguration
  testsuite/pom.xml
Labels: master
