Repository resteasy/resteasy, pull requests merged in 2018-11, with the labels that each got.

#1709 [RESTEASY-2026]: Priority override MUST be taken into account when registering
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyProviderFactoryImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/ProviderContextInjectionEnumContextResolver.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/resource/ProviderContextInjectionTextPlainEnumContextResolver.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/PriorityTest.java
Labels: master

#1716 [RESTEASY-1142] ExceptionHandler: catch IllegalStateException from ClientResponse
  resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLoggerImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingEnableTracingRequestFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingPleaseMapException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingPleaseMapExceptionMapper.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
Labels: master

#1721 [RESTEASY-1996] Added default ParamConverter for multiple element
  docbook/reference/en/en-US/modules/StringConverter.xml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/AbstractCollectionProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/ProcessorFactory.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/AbstractInvocationCollectionProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/CookieParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/FormParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/AbstractWebTargetCollectionProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/MatrixParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/PathParamProcessor.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/QueryParamProcessor.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/annotations/Separator.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/MultiValuedAbstractParamConverter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/MultiValuedArrayParamConverter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/MultiValuedCollectionParamConverter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/MultiValuedParamConverterProvider.java
  resteasy-core/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDefaultParamConverterProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDefaultParamConverterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterConstructorClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterCookieResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterCookieResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterFromStringClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterHeaderDelegate.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterHeaderDelegateClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterHeaderResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterHeaderResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterMatrixResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterMatrixResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterMiscResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterMiscResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterParamConverter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterParamConverterClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterParamConverterProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterPathResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterPathResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterQueryResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterQueryResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/MultiValuedParamDefaultParamConverterValueOfClass.java
Labels: Do Not Merge, master

#1767 [RESTEASY-2064] Prepare test for yasson/issues/152 - setter with multiple arguments
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/SetMethodWithMoreArgumentsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Dog.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/SetMethodWithMoreArgumentsResource.java
Labels: 3.6

#1766 [RESTEASY-2064] Prepare test for yasson/issues/152 - setter with multiple arguments
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/SetMethodWithMoreArgumentsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Dog.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/SetMethodWithMoreArgumentsResource.java
Labels: master

#1762 RESTEASY-2054 - fix broken resteasy-wadl test
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestWadlFunctions.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLNettyContainerTest.java
Labels: master

#1761 [RESTEASY-2053] JDK11 illegal reflective access testsuite warnings
  resteasy-dependencies-bom/pom.xml
Labels: master

#1760 [RESTEASY-2053] JDK11 illegal reflective access testsuite warnings
  resteasy-dependencies-bom/pom.xml
Labels: 3.6

#1769 [RESTEASY-2059] HeaderDelegates are treated as providers.
  docbook/reference/en/en-US/modules/_HeaderParam.xml
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyProviderFactoryImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/HeaderDelegateAsProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/HeaderDelegateAsProviderHeader.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/HeaderDelegateAsProviderHeaderDelegate.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/HeaderDelegateAsProviderResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/HeaderDelegateHeader.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/HeaderDelegateHeaderDelegate.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/resource/param/javax.ws.rs.ext.Providers_HeaderDelegateAsProvider
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/HeaderDelegateTest.java
Labels: master

#1775 [RESTEASY-2066] Upgrade wildfly-arquillian-container dependencies
  resteasy-dependencies-bom/pom.xml
Labels: master

#1774 [RESTEASY-2066] Upgrade wildfly-arquillian-container dependencies
  resteasy-dependencies-bom/pom.xml
Labels: 3.6

#1771 [RESTEASY-2061] exclude jaxb-api archive from resteasy-multipart-prov…
  providers/jaxb/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#1782 [RESTEASY-1619] Do not set compression quality for compression algori…
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/IIOImageProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/iioimage/IIOImageProviderTest.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/iioimage/test1.png
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/iioimage/test2.png
Labels: master

#1784 [RESTEASY-2072] Update TypesBuiltInTest to use ParamConverter
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/TypesBuiltInTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesParamConverterPOJO.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesTestProvider.java
Labels: 3.6

#1783 [RESTEASY-2072] Update TypesBuiltInTest to use ParamConverter
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/TypesBuiltInTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesParamConverterPOJO.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesTestParamConverterProvider.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/resource/TypesTestParamConverterProviderSubclass.java
Labels: 3.6
