Repository resteasy/resteasy, pull requests merged in 2018-10, with the labels that each got.

#1719 RESTEASY-2018 get rid of ee8.preview.mode leftovers
  testsuite/pom.xml
Labels: 3.6

#1720 [RESTEASY-2036] Upgrade to JAXB 2.3.1
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  providers/jaxb/pom.xml
  resteasy-dependencies-bom/pom.xml
  resteasy-stats/pom.xml
Labels: master

#1724 [RESTEASY-2029] Test with JDK11 on Travis CI
  .travis.yml
Labels: 3.6.1.SPx

#1723 [RESTEASY-2036] Upgrade to JAXB 2.3.1
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  providers/jaxb/pom.xml
  resteasy-dependencies-bom/pom.xml
  security-legacy/skeleton-key-idm/skeleton-key-core/pom.xml
Labels: 3.6.1.SPx

#1722 [RESTEASY-2036] Upgrade to JAXB 2.3.1
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  providers/jaxb/pom.xml
  resteasy-dependencies-bom/pom.xml
  security-legacy/skeleton-key-idm/skeleton-key-core/pom.xml
Labels: 3.6

#1711 [RESTEASY-2028] Prepare test for error message length
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/ResponseTrimmingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/ResponseTrimmingResource.java
Labels: 3.6

#1726 [RESTEASY-2037] Fix treatment of unhandled asynchronous exceptions
  resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncUnhandledExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncUnhandledExceptionResource.java
Labels: master

#1732 [RESTEASY-1998] Prepare test for resteasy.preferJacksonOverJsonB property for client on deployment
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/PreferJacksonOverJsonBClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/PreferJacksonOverJsonBClientResource.java
Labels: master

#1733 [RESTEASY-1998] Prepare test for resteasy.preferJacksonOverJsonB property for client on deployment
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/PreferJacksonOverJsonBClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/PreferJacksonOverJsonBClientResource.java
Labels: 3.6

#1737 [RESTEASY-2015] Upgrade to Yasson 1.0.2
  resteasy-dependencies-bom/pom.xml
Labels: master

#1740 [RESTEASY-2047] Fix error in regexp
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
Labels: master

#1744 [RESTEASY-2047] Fix error in regexp
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
Labels: 3.6.1.SPx

#1751 [RESTEASY-2052] Upgrade to Vert.x 3.5.4
  resteasy-dependencies-bom/pom.xml
Labels: master

#1747 [RESTEASY-1749] Fix validation behavior for EJBs
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/SimpleViolationsContainer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationSingletonResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationStatefulResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationStatelessResource.java
Labels: master

#1748 [RESTEASY-1749] Fix validation behavior for EJBs
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/SimpleViolationsContainer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationSingletonResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationStatefulResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationStatelessResource.java
Labels: 3.6

#1755 [RESTEASY-2046] Space Improperly Encoded in Content-Disposition Filename
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/EncodingMimeMultipartFormProviderResource.java
Labels: master

#1715 [RESTEASY-2016] updated message format
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/i18n/Messages.java
Labels: master

#1739 [RESTEASY-2045] refactored method
  resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
Labels: master

#1756 [RESTEASY-2046] Space Improperly Encoded in Content-Disposition Filename
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/EncodingMimeMultipartFormProviderResource.java
Labels: 3.6

#1746 [RESTEASY-2042] Fix modules
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs-public/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly12.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloClient.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/pom.xml
Labels: master

#1757 [RESTEASY-2050] updated Spring version, implemented requried changes …
  resteasy-spring/pom.xml
  resteasy-spring/src/test/resources/spring-test-server.xml
  tjws/src/main/java/Acme/Serve/Serve.java
Labels: 3.6

#1743 [RESTEASY-2038] CacheInterceptor uses content type of response as mediatype instead of accept header of request
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientCacheInterceptorTest.java
Labels: master
