Repository resteasy/resteasy, pull requests merged in 2018-03, with the labels that each got.

#1431 Upgrade to slf4j 1.7.25
  resteasy-dependencies-bom/pom.xml
Labels: master

#1435 [RESTEASY-1816] OnComplete callback registered via SseEventSource.register() is not called
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
Labels: master

#1434 [RESTEASY-1815 + RESTEASY-1819] Sse tests
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEnablingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseSmokeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseBroadcastResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeMessageBodyWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeUser.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/sse/OutboundSseEventImplTest.java
Labels: master

#1433 [RESTEASY-1815] Sse tests part2
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseBroadcastResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeResource.java
Labels: 3.5

#1438 [RESTEASY-1820] Patch tests
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/JAXRS21PatchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
Labels: master

#1437 [RESTEASY-1820] Patch tests
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/JAXRS21PatchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
Labels: 3.5

#1447 [RESTEASY-1793] Backporting changes to 3.5
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Labels: 3.5

#1453 [RESTEASY-1832] Eliminate System.out.println + code cleanup
  profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/MockedProfilingTest.java
  profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/ProfilingTest.java
  providers/jackson/src/test/java/org/jboss/resteasy/test/nextgen/providers/jackson/JacksonTest.java
  security-legacy/keystone/keystone-core/src/test/java/org/jboss/resteasy/test/keystone/TokenTest.java
  security-legacy/skeleton-key-idm/skeleton-key-core/src/test/java/org/jboss/resteasy/test/skeleton/key/SkeletonKeyTokenTest.java
  security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/SigningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseSmokeMessageBodyWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/PatchErrorHandlingTest.java
Labels: master

#1429 [RESTEASY-1810] Usage of Map.entrySet instead of keySet in tests
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ContextProvidersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CookieTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HttponlyCookieTest.java
  testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseRedirectTest.java
  testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ContextProvidersTest.java
  testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
  testsuite/legacy-integration-tests/src/test/java/org/jboss/resteasy/test/response/CookieTest.java
Labels: master

#1449 [RESTEASY-1805]
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/LocatorRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/POJOResourceFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/resourcefactory/SingletonResource.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceClass.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceConstructor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceLocator.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/DefaultResourceMethod.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/MethodParameter.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClass.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceClassProcessor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceConstructor.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceLocator.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/metadata/ResourceMethod.java
  resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxRegistry.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxResteasyDeployment.java
Labels: master

#1458 [RESTEASY-1837] check msgs before deploy app
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
Labels: master

#1459 removed --verbose flag to stop printing of header and other info
  testsuite/microprofile-tck/pom.xml
Labels: master

#1461 [RESTEASY-1834]
  .travis.yml
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/javax/json/api/main/module.xml
  jboss-modules/src/main/resources/modules/javax/json/bind/api/main/module.xml
  jboss-modules/src/main/resources/modules/javax/ws/rs/api/main/module.xml
  jboss-modules/src/main/resources/modules/org/bouncycastle/main/module.xml
  jboss-modules/src/main/resources/modules/org/glassfish/javax/json/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-p-provider/main/module.xml
  jboss-modules/src/main/resources/modules/org/reactivestreams/main/module.xml
  resteasy-dependencies-bom/pom.xml
Labels: 3.5

#1464 [RESTEASY-1834] Fixing json modules to allow deploying and testing ag…
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/javax/json/api/main/module.xml
  jboss-modules/src/main/resources/modules/javax/json/bind/api/main/module.xml
  jboss-modules/src/main/resources/modules/javax/ws/rs/api/main/module.xml
  jboss-modules/src/main/resources/modules/org/bouncycastle/main/module.xml
  jboss-modules/src/main/resources/modules/org/glassfish/javax/json/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-p-provider/main/module.xml
  jboss-modules/src/main/resources/modules/org/reactivestreams/main/module.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#1463 [RESTEASY-1844] Java 9 cleanup, preparation for Java 10+
  pom.xml
  resteasy-jaxrs/pom.xml
Labels: master

#1442 [RESTEASY-1826] added plugins to generated i18n files
  providers/json-binding/pom.xml
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingAnnotationsJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/Cat.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/resource/JsonBindingResource.java
Labels: master

#1466 [RESTEASY-1840] Sync surefire version in whole TS, extract versions t…
  pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: master

#1387 [RESTEASY-1735] Test coverage.
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
Labels: 3.0

#1471 [RESTEASY-1840] Update guidance for new tests
  testsuite/README.MD
Labels: master

#1472 [RESTEASY-1840] Update guidance for new tests
  testsuite/README.MD
Labels: 3.5

#1473 [RESTEASY-1851]:Add jsonp provider for JsonString and JsonNumber
  providers/json-p-ee7/src/main/java/org/jboss/resteasy/plugins/providers/jsonp/JsonObjectProvider.java
  providers/json-p-ee7/src/main/java/org/jboss/resteasy/plugins/providers/jsonp/JsonValueProvider.java
  providers/json-p-ee7/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonp/JsonpTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonp/resource/JsonpResource.java
Labels: master
