Repository resteasy/resteasy, pull requests merged in 2018-07, with the labels that each got.

#1592 [RESTEASY-1932]
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java
Labels: master

#1593 [RESTEASY-1932]
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/ClientResponseFilterExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/resource/ClientResponseFilterExceptionResourceImpl.java
Labels: 3.6

#1589 [RESTEASY-1890] Implement all the server side tracing events.
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/ClassNode.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyServerTracingEvent.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingUtils.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/BasicTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/Foo.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/FooLocator.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/OnDemandTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingApp.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/tracing/logging.properties
Labels: master

#1534 [Resteasy 1863] (2): SseEventSourceImpl should not close http client engine
  profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
  resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#1596 [RESTEASY-1943] Async filter resume with exception issues
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractAsynchronousResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerRequestContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/SuspendableContainerResponseContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncRequestFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncFilterException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncFilterExceptionMapper.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilterResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
Labels: master

#1599 OnComplete callback registered via SseEventSource.register() must be called only once
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSourceTest.java
Labels: master

#1602 [RESTEASY-1922] Exclude interfaces
  resteasy-servlet-initializer/src/main/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializer.java
Labels: master

#1603 Use JDK10 on Travis CI
  .travis.yml
Labels: master

#1606 [RESTEASY-1951]
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  docbook/reference/en/en-US/modules/Using_Path.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/MethodExpression.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientErrorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/Jaxrs20MatchingResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/jaxrs_2_0_web.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/jaxrs_2_1_web.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Default.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Jaxrs20.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/core/basic/Jaxrs20MatchingTest_Jaxrs21.xml
Labels: 3.6

#1609 [RESTEASY-1708]
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/JaxrsInterceptorRegistry.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/NameBoundCDIProxiesTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundProxiesAnnotation.java
Labels: master

#1610 [RESTEASY-1708]
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/JaxrsInterceptorRegistry.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/NameBoundCDIProxiesTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundCDIProxiesResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/resource/NameBoundProxiesAnnotation.java
Labels: 3.6

#1611 [RESTEASY-1959] Removal of unused imports in JaxrsWithSpringMVCTest
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java
Labels: master

#1512 [RESTEASY-1725] Registering lambda context resolver results in ArrayIndexOutOfBoundsException
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
Labels: Requires rebase, master

#1614 [RESTEASY-1884] Use custom manually started container for GZIP tests instead of surefire execution
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerNotAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: master

#1615 [RESTEASY-1884] Use custom manually started container for GZIP tests instead of surefire execution
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/AllowGzipOnServerNotAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/GzipAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAbstractTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/gzip/NotAllowGzipOnServerNotAllowGzipOnClientTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: 3.6

#1618 [RESTEASY-1930] NullEntityProxyTest, VariantAcceptTest
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/NullEntityProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantAcceptTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/VariantAcceptResource.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: master

#1617 [RESTEASY-1930] NullEntityProxyTest, VariantAcceptTest
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  testsuite/integration-tests-spring/deployment/src/test/resources/arquillian.xml
  testsuite/integration-tests-spring/inmodule/src/test/resources/arquillian.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/NullEntityProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/VariantAcceptTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/VariantAcceptResource.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: 3.6

#1619 [RESTEASY-1966] added hibernate archive and HibernateValidatorPermission
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/CustomExceptionMapperTest.java
Labels: master

#1621 [RESTEASY-1964] changed check of response string
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
Labels: master

#1623 [RESTEASY-1963] added read permission
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/ContextTest.java
Labels: master

#1629 [RESTEASY-1941] Fix typo
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvokerImpl.java
  resteasy-rxjava2/src/main/java/org/jboss/resteasy/rxjava2/FlowableRxInvokerImpl.java
  resteasy-rxjava2/src/main/java/org/jboss/resteasy/rxjava2/ObservableRxInvokerImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#1597 [RESTEASY-1890] [RESTEASY-1892]
  providers/jackson/src/test/java/org/jboss/resteasy/test/nextgen/providers/jackson/JacksonTest.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AbstractCollectionFormInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractReaderInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractWriterInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ClientReaderInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ClientWriterInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerReaderInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerWriterInterceptorContext.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/InterceptorTimestampPair.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyMsgTraceEvent.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLogger.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingUtils.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Hex.java
  resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_en.properties
  resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_en_US.properties
  resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_xx.properties
  resteasy-jaxrs/src/test/resources/i18n/Messages.i18n_xx_YY.properties
  security/resteasy-crypto/src/test/resources/i18n/Messages.i18n_en.properties
  security/resteasy-crypto/src/test/resources/i18n/Messages.i18n_xx.properties
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/BasicTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/OnDemandTracingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingApp.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingTestBase.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/tracing/logging.properties
  tjws/src/main/java/Acme/Serve/FileServlet.java
  tjws/src/main/java/org/jboss/resteasy/test/BaseResourceTest.java
Labels: master

#1628 [Testsuite] Define jboss.bind.address.management address for spring i…
  testsuite/integration-tests-spring/deployment/src/test/resources/arquillian.xml
Labels: master
