Repository resteasy/resteasy, pull requests merged in 2018-08, with the labels that each got.

#1625 [RESTEASY-1975] test rewritten with contents of original RESTEASY-108…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/FooResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/TestApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/TestServlet.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/basic/RESTEASY-1082.war
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/basic/web-resteasy1082.xml
Labels: master

#1635 [RESTEASY-1956] Removing FactoryFinder abstraction, as we're back wit…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/FactoryFinder.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Labels: master

#1631 [RESTEASY-1933] Provide an alternative way to set and get ObjectWrite…
  docbook/reference/en/en-US/modules/Json.xml
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyObjectWriterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierConditionalFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierMultipleFilter.java
Labels: master

#1637 [RESTEASY-1933] Provide an alternative way to set and get ObjectWrite…
  docbook/reference/en/en-US/modules/Json.xml
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyObjectWriterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierConditionalFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/resource/ObjectWriterModifierMultipleFilter.java
Labels: 3.6

#1638 [RESTEASY-1975] test rewritten with contents of original RESTEASY-108…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/FooResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/TestApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/resource/resteasy1082/TestServlet.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/basic/RESTEASY-1082.war
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/basic/web-resteasy1082.xml
Labels: 3.6

#1639 Fix minor error in documentation
  docbook/reference/en/en-US/modules/StringConverter.xml
Labels: master

#1640 [RESTEASY-1937] Completely revisiting MP REST Client 1.0 implementati…
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ConfigurationWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/DefaultResponseExceptionMapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ExceptionMapping.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocation.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvocationBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientInvoker.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPClientWebTarget.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClient.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MPResteasyProviderFactory.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/PartialResponse.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ProxyInvocationHandler.java
  resteasy-dependencies-bom/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: master

#1647 [RESTEASY-1934] test changes to fix ResteasyProviderFactory leaks and…
  providers/jaxb/src/main/java/org/jboss/resteasy/plugins/providers/jaxb/SecureUnmarshaller.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/doseta/DosetaKeyRepository.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/DecoratorsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EventsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientDynamicFeaturesTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/MediaTypeCaseSensitivityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/PriorityExecutionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/CustomConstrainedFeatureTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlJAXBContextFinderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/ProviderPriorityProvidersInApplicationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/priority/ProviderPriorityProvidersRegisteredProgramaticallyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/HeaderDelegateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava1Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationThroughRestTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/CDIValidationCoreTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/MultipleWarTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/ProviderInjectionTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/PriorityEqualityTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/CacheControlTest.java
Labels: 3.6

#1645 [RESTEASY-1980] Deal with empty streams
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
Labels: master

#1644 [RESTEASY-1980] Deal with empty streams
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-json-binding-provider/main/module.xml
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
Labels: 3.6

#1652 [RESTEASY-1748] Added "value" parameter to @webfilter and @WebServlet annotations,
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Filter30Dispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
Labels: master

#1653 [RESTEASY-1748] Added "value" parameter to @webfilter and @WebServlet
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Filter30Dispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
Labels: 3.6

#1655 [RESTEASY-1993] Removing jsonb api dependency from resteasy-jaxrs
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/FindAnnotation.java
Labels: master

#1656 [RESTEASY-1993] Removing jsonb api dependency from resteasy-jaxrs
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/FindAnnotation.java
Labels: 3.6

#1648 RESTEASY-1983: Instances built from org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget must inherit of a detached snaphot of the parent configuration
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/LocalResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ConfigurationInheritenceTest.java
Labels: master

#1661 [RESTEASY-1995] remove unused imports from JaxrsWithSpringMVCTest
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java
Labels: 3.6

#1662 [RESTEASY-1995] remove unused imports from JaxrsWithSpringMVCTest
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java
Labels: 3.6.1.SPx

#1673 [RESTEASY-2001] Upgrade to BouncyCastle 1.60
  resteasy-dependencies-bom/pom.xml
Labels: master

#1671 [RESTEASY-1999] Do not use specific rxjava dependency in TS
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilRxJava.java
  testsuite/integration-tests/pom.xml
Labels: master

#1669 [RESTEASY-1999] Do not use specific rxjava dependency in TS
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilRxJava.java
  testsuite/integration-tests/pom.xml
Labels: 3.6

#1670 [RESTEASY-1999] Do not use specific rxjava dependency in TS
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilRxJava.java
  testsuite/integration-tests/pom.xml
Labels: 3.6.1.SPx

#1657 Modules cleanup
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs-api/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs-services/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  pom.xml
  resteasy-client/pom.xml
  resteasy-jaxrs-services/pom.xml
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/resources/META-INF/services/javax.ws.rs.ext.RuntimeDelegate
Labels: master

#1674 [RESTEASY-2001] Upgrade to BouncyCastle 1.60
  resteasy-dependencies-bom/pom.xml
Labels: 3.6

#1665 RESTEASY-1983: Code review
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Labels: master

#1663 RESTEASY_3.6-1983: Instances built from org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget must inherit of a detached snaphot of the parent configuration
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/LocalResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/InterceptorRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  security-legacy/keystone/keystone-core/src/test/java/org/jboss/resteasy/test/keystone/TokenTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ConfigurationInheritenceTest.java
Labels: 3.6

#1679 [RESTEASY-1984] MicroProfile Rest Client chapter in User Guide.
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/MicroProfile_Rest_Client.xml
Labels: master

#1680 [RESTEASY-1984] MicroProfile Rest Client chapter in User Guide.
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/MicroProfile_Rest_Client.xml
Labels: 3.6

#1594 [JBEAP-10146] added permissions to deployed archive
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/AddSpringResteasyAsResourceRootInModuleTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/ContactsTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/TypeMappingTest.java
Labels: master
