Repository resteasy/resteasy, pull requests merged in 2019-07, with the labels that each got.

#2087 Vertx improvements
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  pom.xml
  resteasy-client-vertx/pom.xml
  resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/InputStreamAdapter.java
  resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
  resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/InputStreamAdapterTest.java
  resteasy-client-vertx/src/test/java/org/jboss/resteasy/test/client/vertx/VertxClientEngineTest.java
  resteasy-dependencies-bom/pom.xml
Labels: master

#2085 [RESTEASY-2291] Native image improvements for MP REST Client on Quarkus
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ProviderFactoryTest.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/SslTest.java
Labels: master

#2088 [RESTEASY-2295] Clean up SmallRye versions
  resteasy-dependencies-bom/pom.xml
Labels: master

#2089 [RESTEASY-2293] Upgrade Vert.x to 3.7.1
  resteasy-dependencies-bom/pom.xml
Labels: 3.8

#2090 [RESTEASY-2294] Update to MP REST Client 1.3.3
  resteasy-dependencies-bom/pom.xml
Labels: master

#2101 [RESTEASY-2298] ReaderInterceptorContext.getHeaders() must return a
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ReaderInterceptorContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextResource.java
Labels: 3.8

#2106 [RESTEASY-2299] ReaderInterceptorContext.getHeaders() must return a
  resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ReaderInterceptorContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextResource.java
Labels: 4.1

#2105 [RESTEASY-2299] ReaderInterceptorContext.getHeaders() must return a
  resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ReaderInterceptorContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ReaderInterceptorContextResource.java
Labels: master

#2094 [RESTEASY-2160] Improve SseBroadcasterTest#testErrorListeners
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Labels: master

#2084 RESTEASY-2287 Add complete tests for different optional paramter types
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java
Labels: master

#1985 ResteasyJackson2Provider: fix ConcurrentHashMap contention
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
Labels: master

#2109 [RESTEASY-2304] ResteasyJackson2Provider: fix ConcurrentHashMap conte…
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
Labels: 3.9

#2107 [RESTEASY-2302] Memory usage improvements for client configuration inheritance
  resteasy-core/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/JaxrsInterceptorRegistryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ClientHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ServerHelper.java
Labels: master

#2111 [RESTEASY-2308] Upgrade to jackson-databind 2.9.9.1
  resteasy-dependencies-bom/pom.xml
Labels: master

#2083 [Resteasy-2285] Use LocalResteasyProviderFactory instead of ResteasyProviderFactoryImpl
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/LocalResteasyProviderFactory.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
Labels: master

#2115 [RESTEASY-2310] Give more time to AsyncResponseCallback.assertCalled().
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/AsyncResponseCallback.java
Labels: 3.9

#2116 [RESTEASY-2310] Give more time to AsyncResponseCallback.assertCalled().
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/AsyncResponseCallback.java
Labels: master

#2117 [RESTEASY-2308] Upgrade Jackson databind to 2.9.9.2
  resteasy-dependencies-bom/pom.xml
Labels: master

#2118 [RESTEASY-2308] Upgrade Jackson databind to 2.9.9.2
  resteasy-dependencies-bom/pom.xml
Labels: 3.9

#2114 [RESTEASY-2312] Introduce support for Spring REST annotation handling
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-spring-web/main/module.xml
  pom.xml
  resteasy-bom/pom.xml
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/Registry.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/metadata/Parameter.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/metadata/ResourceBuilder.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-spring-web/pom.xml
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseEntityContainerResponseFilter.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseEntityFeature.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusContainerResponseFilter.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusFeature.java
  testsuite/integration-tests-spring-web/deployment/pom.xml
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/SpringWebTest.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/Greeting.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/ResponseEntityController.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/ResponseStatusController.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/SomeClass.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/TestController.java
  testsuite/integration-tests-spring-web/deployment/src/test/resources/arquillian.xml
  testsuite/integration-tests-spring-web/deployment/src/test/resources/jboss-deployment-structure.xml
  testsuite/integration-tests-spring-web/deployment/src/test/resources/org/jboss/resteasy/test/spring/web/deployment/module/module.xml
  testsuite/integration-tests-spring-web/deployment/src/test/resources/org/jboss/resteasy/test/spring/web/deployment/web.xml
  testsuite/integration-tests-spring-web/pom.xml
  testsuite/pom.xml
Labels: master
