Repository resteasy/resteasy, pull requests merged in 2019-02, with the labels that each got.

#1850 RESTEASY-2099
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/JsonLinkDecorator.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/Book.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStore.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/BookStoreMinimal.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/Comment.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/SecureBookStore.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/SecureBookStoreMinimal.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestFacadeLinks.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestLinks.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/BookStoreInvalidEL.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/el/BookStoreNoPackage.java
Labels: master

#1853 [RESTEASY-2040] disable stream flush with jsonb provider to avoid per…
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
Labels: 3.6.1.SPx

#1846 Ignore charset when checking the content type
  resteasy-jsapi/src/main/resources/resteasy-client.js
Labels: master

#1856 RESTEASY-2149 Comparing incompatible types for equality in resteasy-l…
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/Book.java
Labels: master

#1858 [RESTEASY-1786] DynamicFeature should warn user when registering wrong provider type
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/DynamicFeatureContextDelegate.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/util/DynamicFeatureContextDelegateTest.java
Labels: master

#1859 [RESTEASY-1786] DynamicFeature should warn user when registering wrong provider type
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/DynamicFeatureContextDelegate.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/util/DynamicFeatureContextDelegateTest.java
Labels: 3.6

#1861 [RESTEASY-2149] Fix bug
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/Book.java
Labels: master

#1796 [RESTEASY-2083] Fix issue when SseBroadcasterImpl.notifyOnCloseListeners removes wrong sink from the outputQueue
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Labels: master

#1863 [RESTEASY-2083] Fix issue when SseBroadcasterImpl.notifyOnCloseListen…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcasterTest.java
Labels: 3.6

#1860 [RESTEASY-2148] Enable utf8 encoding of filename only when explicitly…
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartOutput.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/OutputPart.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
Labels: master

#1862 [RESTEASY-1986] Lower log level to DEBUG as the exception is rethrown
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
Labels: master

#1867 [RESTEASY-2097f] Reset streamRead in ClientResponse.resetEntity().
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseWithEntityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/ClientResponseWithEntityResponseFilter.java
Labels: 3.6

#1868 [RESTEASY-2097f] Reset streamRead in ClientResponse.resetEntity().
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientResponseWithEntityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/ClientResponseWithEntityResponseFilter.java
Labels: master

#1872 [RESTEASY-2164] Upgrade to Yasson 1.0.3
  resteasy-dependencies-bom/pom.xml
Labels: master

#1875 [RESTEASY-2166] Review elytron testing
  .travis.yml
  testsuite/README.MD
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
  testsuite/config/enable-elytron-full.cli
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/pom.xml
Labels: 3.7

#1877 [RESTEASY-2166] Review elytron testing
  .travis.yml
  testsuite/README.MD
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
  testsuite/config/enable-elytron-full.cli
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/pom.xml
Labels: master

#1851 [RESTEASY-1952] Unable to set proxy via JAX-RS API
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
Labels: master

#1878 RESTEASY-2161 remove @NoJackson annotation #1869 (rebased)
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/I18N.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  docbook/reference/en/en-US/modules/Jaxb.xml
  docbook/reference/en/en-US/modules/Json-p.xml
  docbook/reference/en/en-US/modules/Json.xml
  docbook/reference/en/en-US/modules/Links.xml
  providers/jackson2/src/main/java/org/jboss/resteasy/annotations/providers/NoJackson.java
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  testsuite/README.MD
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/Jackson2XmlProduct.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/Jackson2XmlResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/JacksonJaxbCoexistenceXmlProduct.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/resource/JacksonJaxbCoexistenceXmlResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/FavoriteMovie.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/FavoriteMovieXmlRootElement.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/FavoriteMovieXmlType.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/Jackson2MovieResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/MovieMap.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/resource/xxeJackson/ObjectFactory.java
Labels: master
