Repository resteasy/resteasy, pull requests merged in 2019-08, with the labels that each got.

#2128 resteasy-bom fixes as a consequence of RESTEASY-1864 changes
  resteasy-bom/pom.xml
Labels: 3.9

#2127 [RESTEASY-2317] Fix bom
  resteasy-bom/pom.xml
Labels: master

#2121 [RESTEASY-2311] permission additions for spring tests. Arquillian ar…
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ConstructorInjectorImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-dependencies-bom/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/AddSpringResteasyAsResourceRootTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/ContactsDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JavaConfigDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/RequestScopedBeanDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/SpringBeanProcessorDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
Labels: Requires rebase, master

#2122 [RESTEASY-2179] updated arquillian versions; Added security manage c…
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/SpringBeanProcessorDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncPostProcessingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyClassloaderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/VerifyDecryptTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigServletContextListenerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigServletTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/CustomJackson2ProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/HomecontrolCustomJAXBContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/wadl/DeploymentTest.java
Labels: Requires rebase, master

#2130 [RESTEASY-2318] Upgrade jackson-databind to 2.9.9.3
  resteasy-dependencies-bom/pom.xml
Labels: master

#2133 [RESTEASY-2323] Upgrade to Undertow 2.0.23.Final
  resteasy-dependencies-bom/pom.xml
Labels: master

#2134 RESTEASY-2085 index.html (welcome-file in web.xml) is broken on Tomcat
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
Labels: master

#2137 RESTEASY-2085 index.html (welcome-file in web.xml) is broken on Tomcat (branch 3.9)
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServlet30Dispatcher.java
Labels: 3.9

#2141 [RESTEASY-2329] Remove unnecessary array copy and resizing for headers
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/MultivaluedTreeMap.java
Labels: master

#2139 [RESTEASY-2311] permission additions for spring tests. Arquillian ar…
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ConstructorInjectorImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-dependencies-bom/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/AddSpringResteasyAsResourceRootTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/ContactsDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JavaConfigDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/JaxrsWithSpringMVCTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/RequestScopedBeanDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/SpringBeanProcessorDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
Labels: master

#2142 [RESTEASY-2331] Refactor hardcoded servlet dependencies
  providers/pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/HttpRequest.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyAsynchronousContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/AsynchronousDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyHttpServletRequestWrapper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyHttpServletResponseWrapper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousExecutionContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ContainerResponseContextImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSourceImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSourceImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSourceImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/GZIPDecodingInterceptor.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/BaseHttpRequest.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/Cleanable.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/Cleanables.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletInputMessage.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriInfo.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/DelegatingHttpRequest.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/HttpServletRequestDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/StringContextReplacement.java
  server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-vertx/pom.xml
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpResponse.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/VertxTest.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncFilterException.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncFilterExceptionMapper.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncPreMatchRequestFilter1.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncPreMatchRequestFilter2.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncPreMatchRequestFilter3.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter1.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter2.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter3.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilterResource.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilterTest.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResource.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter1.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter2.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter3.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncTest.java
Labels: master

#2145 RESTEASY-2332
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/_OptionalParam.xml
Labels: master

#2146 RESTEASY-2332 (for branch 3.9)
  docbook/reference/en/en-US/master.xml
  docbook/reference/en/en-US/modules/_OptionalParam.xml
Labels: 3.9

#2136 RESTEASY-2325 : Add request timeout support for Reactor Netty HttpClient
  .gitignore
  resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
  resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
Labels: master

#2140 [RESTEASY-2328] Use CopyOnWriteMap to prevent map copies with each We…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ThreadLocalResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ClientHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/CopyOnWriteMap.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/test/java/org/jboss/resteasy/core/providerfactory/CopyOnWriteMapTest.java
Labels: master

#2147 [RESTEASY-2279] Update guava version
  providers/jackson2/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#2149 Revert "[RESTEASY-2265] Added intf and impl for endpoint statistics c…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/LocatorRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceLocatorInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/statistics/MethodStatisticsLogger.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/statistics/StatisticsController.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/statistics/MethodStatisticsLoggerImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/statistics/StatisticsControllerImpl.java
Labels: 3.9, Do Not Merge
