Repository resteasy/resteasy, pull requests merged in 2019-09, with the labels that each got.

#2157 [RESTEASY-2346] Fix bug in Spring ResponseEntity headers handling
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseEntityContainerResponseFilter.java
Labels: master

#2158 [RESTEASY-2342] string treated as primitive (#2154)
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/StringToPrimitive.java
Labels: 3.10

#2036 [RESTEASY-2249] Fixing private PostConstruct method detection
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/util/Types.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBResource.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
Labels: master

#2161 [JBEAP-17580] Fixing private PostConstruct method detection
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Types.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBResource.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
Labels: 3.6.1.SPx

#2166 RESTEASY-2335 RestEasy Microprofile Client has a immutable template p…
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Resource.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Test.java
Labels: master

#2168 RESTEASY-2335 RestEasy Microprofile Client has a immutable template problem/bug
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Resource.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/RESTEASY_2335_Test.java
Labels: 3.10

#2167 [RESTEASY-2042] module.xml in resteasy-jaxrs is missing dependency to microprofile-config-api
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jackson-provider/main/module.xml
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly12.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloClient.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/pom.xml
Labels: 3.6.1.SPx

#2135 RESTEASY-2324: RESTEasy client should disable Apache Http Client cookie management feature by default
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientCookieTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
Labels: master

#2169 [RESTEASY-2324] Renaming method on ResteasyClientBuilder
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
Labels: master

#2171 [RESTEASY-2027, RESTEASY-2281] PatchMethodFilter doesn't handle request of MediaType…
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
Labels: 3.6.1.SPx

#2160 Resteasy 2347 json binding provider resteasy configuration null
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/JsonBindingProvider.java
  testsuite/unit-tests/pom.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/JsonBindingTest.java
Labels: master

#2174 [RESTEASY-2350] Upgrade to Jackson 2.9.10
  resteasy-dependencies-bom/pom.xml
Labels: master
