Repository resteasy/resteasy, pull requests merged in 2019-03, with the labels that each got.

#1879 ResteasyProviderFactory refactoring / optimization
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/LocalResteasyProviderFactory.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ThreadLocalResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerReaderInterceptorContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/ServerWriterInterceptorContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ClientHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ExtSortedKey.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/NOOPClientHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/NOOPServerHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ServerHelper.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/SortedKey.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/Utils.java
  resteasy-core/src/main/java/org/jboss/resteasy/mock/MockDispatcherFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/CacheControlDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/CookieHeaderDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/DateDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/EntityTagDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/LinkDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/LinkHeaderDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/LocaleDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/UriHeaderDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/InboundSseEventImpl.java
  resteasy-core/src/main/resources/META-INF/services/javax.ws.rs.ext.RuntimeDelegate
  resteasy-jsapi/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jwt/JsonSerialization.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/InContainerClientBenchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/resource/InContainerClientResource.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ConfigurationInheritanceTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/HeaderDelegateTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/MultipurtContainsJsonTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/PriorityEqualityTest.java
Labels: Do Not Merge, master

#1883 [RESTEASY-2164] Upgrade to Yasson 1.0.3
  resteasy-dependencies-bom/pom.xml
Labels: 3.7

#1882 [RESTEASY-2173] Move towards WildFly 16
  .travis.yml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly13.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJaxbCoexistenceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ProxyWithGenericReturnTypeJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/pom.xml
Labels: master

#1881 [RESTEASY-2173] Move towards WildFly 16
  .travis.yml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly13.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/JacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson/ProxyWithGenericReturnTypeJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJaxbCoexistenceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/ProxyWithGenericReturnTypeJacksonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/pom.xml
Labels: 3.7

#1880 Misc minor perf improvements
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/registry/SegmentNode.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventSinkInterceptor.java
Labels: Do Not Merge, master

#1873 [RESTEASY-1364] Changed exception handling code for constructor metho…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/NotFoundException.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ConstructorInjectorImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/MatrixParamInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/PathParamInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/QueryParamInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/JaxrsAsyncServletTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/ResourceConstructorParamsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorNoParamsResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParams400Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParams404Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParamsMixedResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/Item.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ItemParamConverterProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/FormParamTest.java
Labels: master

#1890 [RESTEASY-754] Ported code from 2014 PR into current master. Add mod…
  jboss-modules/build.xml
  jboss-modules/pom.xml
  jboss-modules/src/main/resources/modules/org/apache/james/mime4j/main/module.xml
  providers/multipart/pom.xml
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4jWorkaroundBinaryEntityBuilder.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartRelatedInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/i18n/Messages.java
  resteasy-dependencies-bom/pom.xml
  security/resteasy-crypto/pom.xml
Labels: master

#1892 [RESTEASY-2110] Fixing issue with JPMS / JDK9+
  resteasy-core/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
  resteasy-dependencies-bom/pom.xml
Labels: master

#1906 [RESTEASY-2171] JsonBindingProvider use incorrect charset encoding
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: master

#1909 [RESTEASY-2103] Remove distinction in validation between field and
  arquillian/RESTEASY-1056-jetty-bv11/src/test/java/org/jboss/resteasy/test/resteasy1056/MissingCDITest.java
  docbook/reference/en/en-US/modules/Validation.xml
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/ConstraintTypeUtil11.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/ConstraintTypeUtilImpl.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/ResteasyViolationExceptionImpl.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ConstraintType.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/CustomExceptionMapperTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ExecutableValidationDisabledTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/GetterReturnValueValidatedTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/PathSuppressionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ResteasyViolationExceptionRepresentationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidateOnExecutionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationComplexTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationCoreTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationHibernateI18NTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationJaxbTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationNullErrorValueTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationOnGetterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationSuppressPathTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ValidationXMLTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/CDIValidationCoreTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/CDIValidationSessionBeanTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/MultipleWarTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/SubresourceValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ValidationSessionBeanTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/CustomExceptionMapperClassConstraint.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/CustomExceptionMapperClassValidator.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/CustomExceptionMapperReport.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/CustomExceptionMapperResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/validation/validation-versioning.customjar
Labels: master

#1908 [RESTEASY-2181] Unify jboss-logging dependencies among providers
  providers/jackson2/pom.xml
  providers/json-binding/pom.xml
  providers/json-p-ee7/pom.xml
  providers/resteasy-atom/pom.xml
Labels: master

#1896 [RESTEASY-2148] Enable utf8 encoding of filename only when explicitly…
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/AbstractMultipartFormDataWriter.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartOutput.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/OutputPart.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
Labels: 3.6.1.SPx

#1915 [RESTEASY-2041] Make servlet api available to users of server adapters.
  server-adapters/resteasy-netty/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  server-adapters/resteasy-netty4/pom.xml
  server-adapters/resteasy-undertow/pom.xml
Labels: master

#1913 [RESTEASY-2180] Turn default async executor into a cached thread pool…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
Labels: master

#1888 [RESTEASY-1404] Client SSL tests
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingOnWildFly14.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWrongHostnameCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslSniHostNamesTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslTestBase.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/resource/CustomTrustManager.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/resource/SslResource.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/client-different-cert.truststore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/client-wildcard-hostname.truststore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/client-wrong-hostname.truststore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/client.truststore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/server-different-cert.keystore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/server-wildcard-hostname.keystore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/server-wrong-hostname.keystore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/server.keystore
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/security/ssl-batch-command.txt
  testsuite/pom.xml
Labels: master

#1920 [RESTEASY-2184] Drop RxJava1 integration (resteasy-rxjava)
  docbook/reference/en/en-US/modules/Reactive.xml
  jboss-modules/pom.xml
  pom.xml
  resteasy-dependencies-bom/pom.xml
  resteasy-rxjava/pom.xml
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableProvider.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvoker.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvokerImpl.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/ObservableRxInvokerProvider.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleProvider.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvoker.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvokerImpl.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/SingleRxInvokerProvider.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/i18n/LogMessages.java
  resteasy-rxjava/src/main/java/org/jboss/resteasy/rxjava/i18n/Messages.java
  resteasy-rxjava/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
  resteasy-rxjava/src/test/java/org/jboss/resteasy/rxjava/Async.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/rxjava/RxInjector.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/rxjava/RxResource.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/rxjava/RxTest.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/test/i18n/I18nMessages_enTestCase.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/test/i18n/I18nMessages_xxTestCase.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  resteasy-rxjava/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
  resteasy-rxjava/src/test/resources/i18n/Messages.i18n_en.properties
  resteasy-rxjava/src/test/resources/i18n/Messages.i18n_xx.properties
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/NoStreamRxTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableSSECompatibilityTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxObservableTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyClientAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleServerAsyncTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/RxSingleTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxNoStreamResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableNoStreamResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableResourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableResourceNoStreamImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxObservableSSECompatibilityResourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxSingleResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/rx/rxjava/resource/RxSingleResourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/StreamRawObservableRxJava1Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/stream/resource/StreamRawObservableRxJava1Resource.java
Labels: master

#1835 Resteasy 1991 response builder built response
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponse.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/AbstractBuiltResponse.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/BuiltResponseEntityNotBacked.java
  resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyView.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ClientFilterResponseBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ResponseBuilderCustomResponseFilter.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/MessageSanitizerMediaTypeTest.java
Labels: master

#1923 [RESTEASY-1887] Fix issue with JPMS
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/ResteasyViolationExceptionMapper.java
  providers/resteasy-validator-provider/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
Labels: master

#1924 [RESTEASY-1887] Fix JPMS issue with resteasy-wadl-undertow-connector
  resteasy-wadl-undertow-connector/src/main/java/org/jboss/resteasy/wadl/undertow/WadlUndertowConnector.java
  resteasy-wadl-undertow-connector/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLUndertowContainerTest.java
Labels: master

#1926 [JBEAP-16542,RESTEASY-2157] Resteasy is not able to load the proxy interface
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ProxyBuilder.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyClassloaderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/resource/ClassloaderResource.java
Labels: 3.6.1.SPx

#1927 [RESTEASY-1887] Fix JPMS issue with tracing classes in split packages
  providers/jackson2/src/main/java/org/jboss/resteasy/tracing/providers/jackson2/Jackson2JsonFormatRESTEasyTracingInfo.java
  providers/jackson2/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
  providers/json-binding/src/main/java/org/jboss/resteasy/tracing/providers/jsonb/JSONBJsonFormatRESTEasyTracingInfo.java
  providers/json-binding/src/main/resources/META-INF/services/org.jboss.resteasy.tracing.api.RESTEasyTracingInfo
Labels: master

#1928 [RESTEASY-1887] Revisiting javax.el and javax.interceptor api depende…
  resteasy-cdi/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#1929 [RESTEASY-2186] Drop resteasy-netty (3)
  distribution/assembly.xml
  distribution/pom.xml
  docbook/reference/en/en-US/modules/I18N.xml
  docbook/reference/en/en-US/modules/RESTEasy_Embedded_Container.xml
  resteasy-bom/pom.xml
  server-adapters/pom.xml
  server-adapters/resteasy-netty/pom.xml
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/HttpServerPipelineFactory.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/HttpsServerPipelineFactory.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyContainer.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpResponse.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyJaxrsServer.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettySecurityContext.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyUtil.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestDispatcher.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RequestHandler.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpRequestDecoder.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/RestEasyHttpResponseEncoder.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/i18n/LogMessages.java
  server-adapters/resteasy-netty/src/main/java/org/jboss/resteasy/plugins/server/netty/i18n/Messages.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/NettyApplicationPathTest.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/NettyTest.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/PortAssigningTest.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/ResteasyTrailingSlashTest.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/i18n/I18nMessages_enTestCase.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/i18n/I18nMessages_xxTestCase.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  server-adapters/resteasy-netty/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesParent.java
  server-adapters/resteasy-netty/src/test/resources/i18n/Messages.i18n_en.properties
  server-adapters/resteasy-netty/src/test/resources/i18n/Messages.i18n_xx.properties
  testsuite/integration-tests/pom.xml
Labels: master

#1932 [RESTEASY-2188] Rely on io.rest-assured:json-path only (we don't need…
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/pom.xml
Labels: master

#1930 [RESTEASY-1991] response builder built response (#1835)
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/AsyncResponseConsumer.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ServerResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/AbstractBuiltResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/BuiltResponseEntityNotBacked.java
  resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyView.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/ClientFilterResponseBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/ResponseBuilderCustomResponseFilter.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/interception/MessageSanitizerMediaTypeTest.java
Labels: 3.7

#1933 [RESTEASY-1887] Further fixes for JPMS
  resteasy-core-spi/pom.xml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  resteasy-links/pom.xml
Labels: master

#1938 [RESTEASY-2193] Clean useless variable in BuiltResponse class
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
Labels: master

#1939 [RESTEASY-2193] Clean useless variable in BuiltResponse class
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
Labels: 3.7

#1952 [RESTEASY-2197] Remove dependency to org.jboss.metadata
  testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/module/module.xml
Labels: master

#1951 [RESTEASY-2197] Remove dependency to org.jboss.metadata
  testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/module/module.xml
Labels: 3.7

#1947 [RESTEASY-2192] remove unneeded methods from AbortedResponse
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
Labels: master

#1946 [RESTEASY-2192] 3.7 branch remove unneeded methods from AbortedResponse
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
Labels: 3.7

#1945 [RESTEASY-2181] Remove usage of deprecated X509HostnameVerifier
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client-api/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/VerifierWrapper.java
  resteasy-client/src/test/java/org/jboss/resteasy/test/i18n/TestMessagesAbstract.java
Labels: master

#1953 [RESTEASY-1404] Fix SslServerWithoutCertificateTest for non-localhost rest run
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslTestBase.java
Labels: 3.7

#1954 [RESTEASY-1404] Fix SslServerWithoutCertificateTest for non-localhost rest run
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithoutCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslTestBase.java
Labels: master

#1949 [RESTEASY-2195] replace sun security code with bouncycastle code to g…
  security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/KeyTools.java
Labels: master

#1948 [RESTEASY-1887] Additional JPMS fixes: more on activation api, transa…
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  pom.xml
  providers/jaxb/pom.xml
  resteasy-cache/resteasy-cache-core/pom.xml
  resteasy-cdi/pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  resteasy-spring/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  server-adapters/resteasy-undertow-spring/pom.xml
  server-adapters/resteasy-undertow-spring/src/test/java/org/jboss/resteasy/springmvc/test/client/BasicSpringTest.java
  testsuite/pom.xml
Labels: master

#1955 [RESTEASY-2181] Fix misc deprecation warnings
  resteasy-client-jetty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/jetty/JettyClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/cache/CacheEntry.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/AbortedResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponse.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientWebTarget.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/DecoratorMatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/messagebody/ReaderUtility.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/messagebody/WriterUtility.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/BuiltResponse.java
  resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java
Labels: master

#1943 [RESTEASY-2171] JsonBindingProvider use incorrect charset encoding
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: master

#1942 RESTEASY-2194 fixing CDI property injector to always work on contextu…
  resteasy-cdi/pom.xml
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/CdiPropertyInjector.java
Labels: master

#1941 RESTEASY-2194 fixing CDI property injector to always work on contextu…
  resteasy-cdi/pom.xml
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/CdiPropertyInjector.java
Labels: 3.7

#1958 [RESTEASY-2131] Implements use of MicroProfile Config.
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-jaxrs/main/module.xml
  providers/multipart/pom.xml
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  resteasy-core/pom.xml
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/FilterBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/FilterDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ListenerBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletContainerDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/PortProvider.java
  resteasy-core/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigServletContextListenerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/MicroProfileConfigServletTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_filter.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_servlet.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_servlet_context_listener.xml
  testsuite/unit-tests/pom.xml
Labels: master

#1959 [RESTEASY-1977] Make server side tracing info to include request instance id
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLogger.java
  resteasy-core/src/main/java/org/jboss/resteasy/tracing/RESTEasyTracingLoggerImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingEnableTracingRequestFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/JsonFormattedTracingInfoTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/tracing/TracingTestBase.java
Labels: master

#1962 [RESTEASY-2171] JsonBindingProvider use incorrect charset encoding
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: 3.7

#1963 RESTEASY-2194 integration test-case
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/RESTEasyParamCdiTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamBeanCdi.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamCdiResource.java
Labels: master

#1934 [RESTEASY-2189] port of RESTEASY-1364 and RESTEASY-2177 changes to 3.7
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  resteasy-jaxrs-testsuite/src/test/java/org/jboss/resteasy/test/finegrain/InternalDispatcherTest.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ExceptionHandler.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MethodInjectorImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/QueryParamInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/request/AcceptHeaders.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/request/QualityValue.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/BadRequestException.java
  resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasyWebArgumentResolver.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/resource/InternalDispatcherForwardingResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceInfoInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/ResourceConstructorParamsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorNoParamsResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParams400Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParams404Resource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorParamsMixedResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/Item.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ItemParamConverterProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/FormParamTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/request/MediaTypeQualityValueTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/request/QualityValueTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/request/StringQualityValueTest.java
Labels: 3.7

#1966 [RESTEASY-2131] Allow ConfigProvider to resolve RESTEasy's configured…
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/PortProvider.java
Labels: master

#1964 RESTEASY-2194 integration test-case
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/RESTEasyParamCdiTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamBeanCdi.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/RESTEasyParamCdiResource.java
Labels: 3.7
