Repository resteasy/resteasy, pull requests merged in 2019-05, with the labels that each got.

#2011 [RESTEASY-2234] Upgrade to HV 6.0.16.Final
  resteasy-dependencies-bom/pom.xml
Labels: master

#2015 [RESTEASY-2198] Ignore media type "application/signed-exchange"
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ByteArrayProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DefaultBooleanWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileRangeWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ReaderProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/StreamingOutputProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/StringTextStar.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/MediaTypeHelper.java
  security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/smime/EnvelopedWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/mediatype/resource/BlacklistedMediaTypeResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeFile1
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeFile2
Labels: master

#2016 [RESTEASY-2198] Ignore media type "application/signed-exchange"
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ByteArrayProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DataSourceProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/DefaultBooleanWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/FileRangeWriter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/ReaderProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/StreamingOutputProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/StringTextStar.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/MediaTypeHelper.java
  security/resteasy-crypto/src/main/java/org/jboss/resteasy/security/smime/EnvelopedWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/mediatype/resource/BlacklistedMediaTypeResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeFile1
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/mediatype/BlacklistedMediaTypeFile2
Labels: 4.0

#2013 [RESTEASY-2232] Don't ignore MessageBodyWriters without @Produces
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/ProviderWithNoProducesTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/Foo.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/ProviderWithNoProducesMessageBodyWriter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/noproduces/resource/ProviderWithNoProducesResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/noproduces/ProviderWithNoProduces_web.xml
Labels: master

#2010 Cleanup httpclient dependencies for resteasy-core
  resteasy-client/pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core/pom.xml
  security/jose-jwt/pom.xml
Labels: 4.0

#2021 [RESTEASY-2228] Allow loading and running MP Config sources contribut…
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSource.java
Labels: master

#2009 [RESTEASY-2230] check for method private declaration
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
Labels: master

#2008 [RESTEASY-2230] 3.7 branch added check of method final declarations
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java
Labels: 3.7

#1898 RESTEASY-1419: add support for injecting Optional<T> parameter types
  resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java
Labels: master

#2026 [RESTEASY-2222] ParamConverter and primitive types
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/PrimitiveParamConverterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterDefaultIntegerResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerConverter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerConverterProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerResource.java
Labels: 3.7

#2030 [RESTEASY-2222] ParamConverter and primitive types
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/PrimitiveParamConverterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterDefaultIntegerResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerConverter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerConverterProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/resource/ParamConverterIntegerResource.java
Labels: master

#2028 [RESTEASY-2176]:Client-side SSL - HostnameVerificationPolicy.STRICT s…
  .travis.yml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
Labels: master

#2027 [RESTEASY-1407] Prevent InputStreamProvider from writing Content-Length when using HttpClient.
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/InputStreamProvider.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Constants.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/inputstream/InputStreamWithEmptyByteArrayTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/inputstream/resource/InputStreamWithEmptyByteArrayInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/inputstream/resource/InputStreamWithEmptyByteArrayResource.java
Labels: 3.7

#2024 [RESTEASY-2227] With CDI enabled, execute any @PostConstruct methods
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/JaxrsInjectionTarget.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/util/Types.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_off.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_on.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
Labels: master

#2018 [RESTEASY-2227] With CDI enabled, execute any @PostConstruct
  jboss-modules/src/main/resources/modules/org/jboss/resteasy/resteasy-cdi/main/module.xml
  resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/JaxrsInjectionTarget.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Types.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionEJBInterceptorResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/injection/resource/PostConstructInjectionResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_off.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/injection/PostConstructInjection_beans_cdi_on.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/injection/PostConstructInjectionTest.java
Labels: 3.7

#2023 [RESTEASY-2127] Allow Multipart XOP to access Providers in context.
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/XopWithMultipartRelatedReader.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/XOPMultipartProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxy.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyGetFileResponse.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyPutFileRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyResource.java
Labels: master

#2019 [RESTEASY-2127] Allow Multipart XOP to access Providers in context.
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/XopWithMultipartRelatedReader.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/XOPMultipartProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxy.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyGetFileResponse.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyPutFileRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/XOPMultipartProxyResource.java
Labels: 3.7

#2031 [RESTEASY-2176]:Client-side SSL - HostnameVerificationPolicy.STRICT
  .travis.yml
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ClientHttpEngineBuilder43.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithWildcardHostnameCertificateTest.java
Labels: 3.7

#2033 RESTEASY-2159 Review multipart provider documentation
  docbook/reference/en/en-US/modules/Multipart.xml
Labels: master

#2043 Rest Client MP 1.2 fork from SmallRye
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/cdi/microprofile/RestClientExtension.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ConfigurationWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/DefaultResponseExceptionMapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ExceptionMapping.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/MicroprofileClientBuilderResolver.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/PartialResponse.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/client/microprofile/ProxyInvocationHandler.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/BuilderResolver.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ConfigurationWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultMediaTypeFilter.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ExceptionMapping.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/InvocationContextImpl.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/MethodInjectionFilter.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/PartialResponse.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ProxyInvocationHandler.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientListeners.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientProxy.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/async/AsyncInterceptorRxInvoker.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/async/AsyncInterceptorRxInvokerProvider.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/async/AsyncInvocationInterceptorHandler.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/async/ExecutorServiceWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeaderFillingException.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeaderProvider.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeaderProviders.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeaderValueGenerator.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeadersRequestFilter.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ComputedHeaderValueFiller.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/HttpHeadersContextProvider.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/IncomingHeadersProvider.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/utils/ClientRequestContextUtils.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/utils/ListCastUtils.java
  resteasy-client-microprofile/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
  resteasy-client-microprofile/src/main/resources/META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientResponseContextImpl.java
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ResponseExceptionMapperRuntimeExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
  testsuite/microprofile-tck/pom.xml
Labels: 3.7

#2042 RESTEASY-2253 - add "Undertow Embedded Spring Container" section into…
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
  server-adapters/resteasy-undertow/pom.xml
Labels: master

#2048 [RESTEASY-2257] MP Rest Client SSL support
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeadersRequestFilter.java
  resteasy-dependencies-bom/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: master

#2049 [RESTEASY-2259] - MP Rest Client 1.3 - configKey support
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
  testsuite/microprofile-tck/pom.xml
Labels: 3.8

#2041 Upgrade Jackson to 2.9.9
  resteasy-dependencies-bom/pom.xml
Labels: master

#2052 [RESTEASY-2259] MP Rest Client 1.3 - configKey support
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientDelegateBean.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
  testsuite/microprofile-tck/pom.xml
Labels: master

#2051 [RESTEASY-2261] MP Rest Client 1.3 - Proxies should be closeable
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ProxyInvocationHandler.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  testsuite/microprofile-tck/pom.xml
Labels: 3.8

#2053 [RESTEASY-2165]:Add json merge patch support
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentResource.java
Labels: master

#2037 [RESTEASY-2251] Test for DynamicFeature
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddDynamicFeature.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/DynamicFeatureResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/GreetingInterceptor.java
Labels: master
