Repository resteasy/resteasy, pull requests merged in 2019-06, with the labels that each got.

#2058 [RESTEASY-2257] Upgrade to MP REST Client 1.3.2
  resteasy-dependencies-bom/pom.xml
Labels: master

#2057 [RESTEASY-2257] Upgrade to MP REST Client 1.3.2
  resteasy-dependencies-bom/pom.xml
Labels: 3.8

#2044 Use Apache-2.0 licensed version of the JCIP annotations
  resteasy-dependencies-bom/pom.xml
  security/jose-jwt/pom.xml
Labels: master

#2063 [RESTEASY-2268] ResteasyHttpHeaders does not follow JAX-RS spec concerning modifiability
  profiling-tests/src/test/java/org/jboss/resteasy/test/profiling/InMemoryClientEngine.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/InternalDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/PreMatchContainerRequestContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/mock/MockHttpRequest.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyHttpHeaders.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/UnmodifiableMultivaluedMap.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/ResteasyHttpHeadersTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/util/UnmodifiableMultivaluedMapTest.java
Labels: master

#2070 Upgrade undertow to 2.0.21.Final
  resteasy-dependencies-bom/pom.xml
Labels: master

#2067 [RESTEASY-2172] branch 3.8 yasson updated to version 1.0.4
  resteasy-dependencies-bom/pom.xml
Labels: 3.8

#2056 [Resteasy-2246] Dynamic features should be resolved once for each resource method
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/interception/JaxrsInterceptorRegistryListener.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/JaxrsInterceptorRegistryImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
Labels: master

#1910 [RESTEASY-2171] JsonBindingProvider use incorrect charset encoding
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/ContainerConstants.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingTest.java
  testsuite/integration-tests/src/test/resources/arquillian.xml
Labels: 3.6.1.SPx

#2076 [RESTEASY-2267] Further fixes to documentation + minor fix to a test…
  docbook/reference/en/en-US/modules/MicroProfile_Rest_Client.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
Labels: master

#2078 [RESTEASY-2271] Documentation and minor refactoring to the test to ha…
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
  resteasy-client-reactor-netty/pom.xml
  resteasy-client-reactor-netty/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngineTest.java
Labels: master

#2080 [WFLY-12235] Use latest jboss-jaxrs-api_2.1_spec
  resteasy-dependencies-bom/pom.xml
Labels: master
