Repository resteasy/resteasy, pull requests merged in 2019-11, with the labels that each got.

#2205 [RESTEASY-2393] Missing executor service shutdown
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
Labels: master

#2206 Component upgrades 6-11-19
  resteasy-dependencies-bom/pom.xml
Labels: master

#2207 [RESTEASY-2402] ClientConfiguration.getClasses() and getInstances()
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientConfigurationImmutableSetsTest.java
Labels: master

#2208 [RESTEASY-2402] ClientConfiguration.getClasses() and getInstances()
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfiguration.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientConfigurationImmutableSetsTest.java
Labels: 3.10

#2211 Fix NPE when ConfigSource is not available
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java
Labels: master

#2210 RESTEASY-828 Issue with injected ServletContext in Resteasy/SpringMVC setup
  resteasy-spring/src/main/java/org/jboss/resteasy/springmvc/ResteasySpringDispatcherServlet.java
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/RESTEasy828Test.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/resource/RESTEasy828Resource.java
  testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/resteasy828/applicationContext.xml
  testsuite/integration-tests-spring/inmodule/src/test/resources/org/jboss/resteasy/test/spring/inmodule/resteasy828/web.xml
Labels: master

#2209 [RESTEASY-2240] ported gzip classes from 3.8 but changed location whe…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
Labels: master

#2218 [RESTEASY-2412] Upgrade Jackson to 2.10.1
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
Labels: 3.10

#2219 [RESTEASY-2412] Upgrade to Jackson 2.10.1
  resteasy-dependencies-bom/pom.xml
Labels: master

#2220 [RESTEASY-2358] Fix duplicate validation violations for EJB resources.
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationEJBProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationEJBProxyGreeterResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationEJBProxyGreeting.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/ejb/web.xml
Labels: master

#2221 [RESTEASY-2358] Fix duplicate validation violations for EJB resources.
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationEJBProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationEJBProxyGreeterResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/resource/EJBCDIValidationEJBProxyGreeting.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/cdi/ejb/web.xml
Labels: 3.10

#2227 [RESTEASY-2422] Add system property for controlling SerializationFeat…
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
Labels: 3.10

#2226 [RESTEASY-2422] Add system property for controlling SerializationFeat…
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonDatatypeTest.java
Labels: 3.9

#2228 [RESTEASY-2423] Support "*" in white-list
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/WhiteListPolymorphicTypeValidatorBuilder.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/WhiteListPolymorphicTypeValidatorCatchAllTest.java
Labels: master

#2229 [RESTEASY-2411] Doc
  docbook/reference/en/en-US/modules/Json.xml
Labels: master

#2233 [RESTEASY-2434] Prevent NPE on non spring-web-annotated methods
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/resource/TestController.java
Labels: master

#2231 Test against WFLY 18.0.1.Final
  .travis.yml
  testsuite/pom.xml
Labels: master
