Repository resteasy/resteasy, pull requests merged in 2020-07, with the labels that each got.

#2453 Fix issue with Spring Web parameters encoding
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spi/metadata/SpringResourceBuilder.java
  testsuite/integration-tests-spring-web/deployment/src/test/java/org/jboss/resteasy/test/spring/web/deployment/SpringWebTest.java
Labels: master

#2461 Disable wiremock banner
  testsuite/microprofile-tck/pom.xml
Labels: master

#2447 [RESTEASY-2571] Follow up at avoiding a NullPointerException of the M…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: master

#2445 [RESTEASY-2622] Avoid a NullPointerException of the MediaType associa…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
Labels: 3.13

#2448 [RESTEASY-2622] Follow up at avoiding a NullPointerException of the M…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpAsyncClient4Engine.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: 4.5

#2468 [RESTEASY-2645] Upgrade Jackson to 2.11.1
  resteasy-dependencies-bom/pom.xml
Labels: master

#2473 Upgrade shrinkwrap to 2.2.7
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#2185 [RESTEASY-2366] Introduce RESTEasy integration with WildFly Elytr…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ClientHttpEngineBuilder43.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/ResteasyClientBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfigProviderFilter.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/spi/ClientConfigException.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/spi/ClientConfigProvider.java
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests-spring/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderBearerTokenTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderTestJarHelper.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigBearerTokenTestMainClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderBearerTokenAbortFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplCredentials.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplMocked.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplWithBearerMocked.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigTestMainClass.java
Labels: 3.13

#2470 [RESTEASY-2366] Introduce RESTEasy integration with WildFly Elytron
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ClientHttpEngineBuilder43.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientConfigProviderFilter.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/spi/ClientConfigException.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/spi/ClientConfigProvider.java
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests-spring/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderBearerTokenTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/ClientConfigProviderTestJarHelper.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SslServerWithCorrectCertificateTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigBearerTokenTestMainClass.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderBearerTokenAbortFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplCredentials.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplMocked.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigProviderImplWithBearerMocked.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/testjar/ClientConfigTestMainClass.java
Labels: master

#2471 [RESTEASY-2646]:Fix match cache in RootNode grows infinitely
  resteasy-core/src/main/java/org/jboss/resteasy/core/registry/MatchCache.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/registry/RootNode.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/test/java/org/jboss/resteasy/core/registry/RootNodeCacheSizeTest.java
Labels: master

#2477 [RESTEASY-2646]:Fix match cache in RootNode grows infinitely
  resteasy-core/src/main/java/org/jboss/resteasy/core/registry/RootNode.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/test/java/org/jboss/resteasy/core/registry/RootNodeCacheSizeTest.java
Labels: 4.5

#2480 Test for RESTEASY-2633
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
Labels: master

#2479 Performance improvements
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/MultivaluedMapImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriInfo.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/Encode.java
Labels: master
