Repository resteasy/resteasy, pull requests merged in 2020-12, with the labels that each got.

#2605 [JBEAP-20177] [RESTEASY-2681] merged changes from keycloak into code base
  security/jose-jwt/pom.xml
  security/jose-jwt/src/main/java/org/jboss/resteasy/crypto/SignatureSignerContext.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/Algorithm.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/AlgorithmType.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSBuilder.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSHeader.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInput.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInputException.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/HMACProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/RSAProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/SignatureProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64Url.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/BouncyIntegration.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/DerUtils.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/JsonSerialization.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Key.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemException.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemUtils.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/jose/JWSTest.java
Labels: 3.11

#2608 3.14.fix
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/pom.xml
Labels: 3.14

#2602 [RESTEASY-2728] Clients running in a resource method throw safer WebApplicationException
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/ThreadLocalStack.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyNewBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyOldBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionNewBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionOldBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyNewBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyOldBehaviorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionExceptions.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/client/exception/wae_web.xml
  testsuite/microprofile-tck/pom.xml
Labels: 3.11

#2620 [RESTEASY-2765] Fix validation of empty array
  resteasy-core-spi/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/EmptyArrayValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/EmptyArrayValidationFoo.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/EmptyArrayValidationResource.java
Labels: master

#2619 [RESTEASY-2765] Fix validation of empty array
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/EmptyArrayValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/EmptyArrayValidationFoo.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/EmptyArrayValidationResource.java
Labels: 3.14

#2613 (rebased)RESTEASY-1784 - Exception during chunked transfer is suppressed
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/HttpResponse.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/SynchronousDispatcher.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/HttpServletResponseWrapper.java
Labels: master

#2609 [RESTEASY-2707] added security block
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: master

#2610 [RESTEASY-2707] added security block
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ApacheHttpClient4Engine.java
Labels: 3.14

#2607 Fix commas in excludedGroups
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/pom.xml
Labels: 3.13

#2603 [RESTEASY-2776] Add support of Optional types in BeanParams
  resteasy-core/src/main/java/org/jboss/resteasy/core/InjectorFactoryImpl.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/OptionalInjectionTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/resource/resource/OptionalResource.java
Labels: master

#2623 [RESTEASY-2728] Clients running in a resource method throw safer WebApplicationException
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  docbook/reference/en/en-US/modules/MicroProfile_Rest_Client.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/ThreadLocalStack.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
Labels: 3.14

#2627 [RESTEASY-2772] Backing out changes for RESTEASY-2772.
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartReader.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mediatype/MediaTypeHeaderTest.java
Labels: 3.14

#2622 [RESTEASY-2766] Upgrade Resteasy to support vert.x 4
  resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
  resteasy-dependencies-bom/pom.xml
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/ChunkOutputStream.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxJaxrsServer.java
Labels: master

#2474 RESTEASY-2650: Use web.xml servlets for app path
  .gitignore
  resteasy-servlet-initializer/pom.xml
  resteasy-servlet-initializer/src/main/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializer.java
  resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/ResteasyServletInitializerTest.java
  resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppAndResource.java
  resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppWithAppPath.java
  resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/AppWithNoAppPath.java
  resteasy-servlet-initializer/src/test/java/org/jboss/resteasy/plugins/servlet/testapp/Resource1.java
Labels: master

#2449 [RESTEASY-2624] Built in MicroProfile ConfigSource should let user override default ordinal
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/BaseServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/FilterConfigSourceImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletConfigSourceImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSource.java
  resteasy-core/src/main/java/org/jboss/resteasy/microprofile/config/ServletContextConfigSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalServletContextListenerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceDefaultOrdinalServletTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalServletContextListenerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/ConfigSourceOverrideOrdinalServletTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/MicroProfileConfigResource.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_filter.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_servlet.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_default_ordinal_servlet_context_listener.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_filter.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_servlet.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/microprofile/config/web_override_ordinal_servlet_context_listener.xml
Labels: Requires rebase, master

#2626 [RESTEASY-2676] replaced example with current code
  docbook/reference/en/en-US/modules/Multipart.xml
Labels: master

#2630 RESTEASY-2742 MicroProfile Config 2.0
  resteasy-dependencies-bom/pom.xml
Labels: master

#2632 [RESTEASY-2781] Clients running in a resource method throw safer WebA…
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-client-api/pom.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
  resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/ThreadLocalStack.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
Labels: master
