Repository resteasy/resteasy, pull requests merged in 2020-11, with the labels that each got.

#2587 [RESTEASY-2747] (3.11) Adding documentation about mutually exclusive usage of -Delytron and -Dts.standalone.microprofile properties
  testsuite/README.MD
Labels: 3.11

#2585 [RESTEASY-2749] (3.11) Remove mail layer tests when executing bootable JAR test profile
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
Labels: 3.11

#2592 [RESTEASY-2749] (3.14) Remove mail layer tests when executing bootable JAR test profile
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
Labels: 3.14

#2586 [RESTEASY-2748] (3.11) Fixing Bouncycastle test deployment structure
  testsuite/integration-tests/src/test/resources/jboss-deployment-structure-bouncycastle.xml
Labels: 3.11

#2593 [RESTEASY-2769] (3.14) Fixing Bouncycastle provisioning for Bootable JAR test executions
  testsuite/integration-tests/pom.xml
Labels: 3.14

#2499 [RESTEASY-2681] merged changes from keycloak into code base
  security/jose-jwt/pom.xml
  security/jose-jwt/src/main/java/org/jboss/resteasy/crypto/SignatureSignerContext.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/Algorithm.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/AlgorithmType.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSBuilder.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSHeader.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInput.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/JWSInputException.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/HMACProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/RSAProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/crypto/SignatureProvider.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Base64Url.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/BouncyIntegration.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/DerUtils.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/JsonSerialization.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/Key.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemException.java
  security/jose-jwt/src/main/java/org/jboss/resteasy/jose/jws/util/PemUtils.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/jose/JWSTest.java
Labels: master

#2454 [RESTEASY-2628] Review scope of properties/provider registered in a dynamic feature
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/DynamicFeatureTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddDynamicFeature.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/AddFeature.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/interceptor/resource/DynamicFeatureResource.java
Labels: master

#2584 Address premature connection close issue with reactor-netty and tomcat
  resteasy-client-reactor-netty/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ReactorNettyClientHttpEngine.java
Labels: Waiting CLA, master

#2564 [RESTEASY-2731] Fix MessageBodyWriter resolving for HEAD requests
  resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java
Labels: Waiting CLA, master

#2597 Avoid NPE for config without dynamicFeatures
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/ClientInvoker.java
Labels: master

#2588 RESTEASY-2734 The current WADL GRAMMAR generation logic incorrectly clean the schema types
  resteasy-wadl-undertow-connector/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLUndertowContainerTest.java
  resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlDefaultResource.java
  resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/MyWadlResource.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLNettyContainerTest.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WadlTests.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/wadl/WadlTestApplication.java
Labels: 3.14

#2589 RESTEASY-2739 - Update WADL section document
  docbook/reference/en/en-US/modules/WADL.xml
Labels: 3.14

#2598 [RESTEASY-2772] changed exception type and adjusted unit tests
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartReader.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mediatype/MediaTypeHeaderTest.java
Labels: master

#2604 [RESTEASY-2778] Prevent the issue from completely failing the build
  resteasy-reactor/src/test/java/org/jboss/resteasy/reactor/ReactorTest.java
  resteasy-rxjava2/src/test/java/org/jboss/resteasy/rxjava2/RxTest.java
Labels: master
