Repository resteasy/resteasy, pull requests merged in 2020-01, with the labels that each got.

#2253 [RESTEASY-2465] removed profile resteasy-dependencies-eap
  pom.xml
Labels: master

#2256 [RESTEASY-1788] Update description of applicable open source licenses.
  docbook/reference/en/en-US/modules/License.xml
Labels: 3.10

#2257 [RESTEASY-1788] Update description of applicable open source licenses.
  docbook/reference/en/en-US/modules/License.xml
Labels: master

#2258 [RESTEASY-2453] Deleted references to resteasy.scan,
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
Labels: 3.10

#2260 Sync 08 01 20
  CONTRIBUTING.md
  README.md
  pom.xml
  providers/jackson2/pom.xml
  providers/jaxb/pom.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/PartialResponse.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
Labels: 3.10

#2265 RESTEASY-2470 Upgrade Hibernate Validator to 6.0.18
  resteasy-dependencies-bom/pom.xml
Labels: master

#2266 RESTEASY-2470 Upgrade Hibernate Validator to 6.0.18
  resteasy-dependencies-bom/pom.xml
Labels: 3.10

#2267 [RESTEASY-2469] Allow manual setup of whitelist validator
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/JacksonConfig.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/WhiteListPolymorphicTypeValidatorManualOverrideTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/land/Automobile2.java
Labels: master

#2269 [RESTEASY-2469] Allow manual setup of whitelist validator
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/JacksonConfig.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/WhiteListPolymorphicTypeValidatorManualOverrideTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/whitelist/model/land/Automobile2.java
Labels: 3.10

#2270 [RESTEASY-1510] Implement "resteasy.disable.providers" parameter.
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/RegisterBuiltin.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/DisabledProvidersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/DisabledProvidersApplication1.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/DisabledProvidersApplication2.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/DisabledProvidersApplication3.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/DisabledProvidersResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/Foo.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/disabled/resource/FooReaderWriter.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/disabled/web_disabled.xml
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/disabled/web_disabled_with_providers.xml
Labels: 3.10

#2263 RESTEASY-2467 updated smallrye-config dependency from 1.3.9 to 1.5.1
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/microprofile-tck/pom.xml
Labels: master

#2271 [RESTEASY-2476] Sync smallrye-config with wfly master
  resteasy-dependencies-bom/pom.xml
Labels: 3.10

#2272 [RESTEASY-2477] Upgrade JAXB
  resteasy-dependencies-bom/pom.xml
Labels: 3.10

#2274 [RESTEASY-2478] Upgrade JAXB
  resteasy-dependencies-bom/pom.xml
Labels: master

#2277 [RESTEASY-2481] Support MicroProfile REST Client 1.4.
  resteasy-client-microprofile/pom.xml
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeaderProviders.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ClientHeadersFactoryCDITest.java
  resteasy-dependencies-bom/pom.xml
Labels: master

#2268 [RESTEASY-2486] Fix for RestEasyClientBuilder http proxy not working
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionClientEngineBuilder.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/URLConnectionEngine.java
Labels: Waiting CLA, master

#2278 [RESTEASY-2474] Migration to Log4j 2
  pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core-spi/src/test/java/org/jboss/resteasy/test/resteasy_jaxrs/i18n/TestLogMessages_Abstract.java
  resteasy-core-spi/src/test/resources/log4j.xml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  security/resteasy-crypto/src/test/java/org/jboss/resteasy/test/security/doseta/EagleDnsTest.java
  security/resteasy-crypto/src/test/resources/log4j.xml
Labels: master
