Repository resteasy/resteasy, pull requests merged in 2020-09, with the labels that each got.

#2507 [RESTEASY-2549] Remove resteasy-validator-provider source dependency …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  docbook/reference/en/en-US/modules/Validation.xml
  providers/resteasy-validator-provider/pom.xml
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/AbstractValidatorContextResolver.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  testsuite/integration-tests-embedded/pom.xml
  testsuite/integration-tests-embedded/src/test/java/org/jboss/resteasy/embedded/test/core/validate/NonCDIValidatorFactoryTest.java
  testsuite/unit-tests/pom.xml
Labels: master

#2506 [RESTEASY-2549] Remove resteasy-validator-provider source dependency …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  docbook/reference/en/en-US/modules/Validation.xml
  providers/resteasy-validator-provider/pom.xml
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/AbstractValidatorContextResolver.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/SimpleViolationsContainer.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/NonCDIValidatorFactoryTest.java
  testsuite/unit-tests/pom.xml
Labels: 3.14

#2508 [RESTEASY-2687] Do not use ResteasyProviderFactory.getInstance() in SseEventProvider
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventProvider.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventSinkInterceptor.java
Labels: master

#2504 [RESTEASY-2684] Statically set provider factory on ResteasyClientBuilderImpl
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ResteasyClientBuilderImpl.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/DefaultResteasyProviderFactoryTest.java
Labels: master

#2501 [RESTEASY-2683] NPE in ApacheHttpClient43Test because cache is null in MediaTypeMap
  resteasy-core/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java
Labels: master

#2500 [RESTEASY-2592] removed profile forward.compatibility and annotation …
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForForwardCompatibility.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/TypeMappingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchCounterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/ResteasyJAXRSImplTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/FilteredCookieTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipSizeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/SigningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/FormUrlEncodedCharsetTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/atom/AtomComplexModelTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/TempFileDeletionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/HeadersInViewResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlHeaderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultMediaTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MultipleEndpointsWarningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceInfoInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/UriInfoTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/TrailingSlashTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/NotFoundErrorMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/PreconditionRfc7232Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HeadContentLengthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
  testsuite/pom.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ResponseBuilderImplTest.java
Labels: master

#2495 RESTEASY-2678 - Fix read priority from @Priority with @RegisterProvider.
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/Utils.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProviderPriority.java
Labels: master

#2511 [RESTEASY-2592] Restore unintentionally disabled testsuites
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/TypeMappingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchCounterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/ResteasyJAXRSImplTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/FilteredCookieTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipSizeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/SigningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/FormUrlEncodedCharsetTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/atom/AtomComplexModelTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/TempFileDeletionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/HeadersInViewResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jaxb/XmlHeaderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MultipleEndpointsWarningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceInfoInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/UriInfoTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/TrailingSlashTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/NotFoundErrorMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/PreconditionRfc7232Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HeadContentLengthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
  testsuite/pom.xml
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ResponseBuilderImplTest.java
Labels: master

#2514 [RESTEASY-2690] Don't create a context if it does not exist
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Labels: 3.14

#2515 Update target containers
  .github/workflows/maven.yml
  .travis.yml
  testsuite/pom.xml
Labels: 3.14

#2517 [RESTEASY-2674] RESTEASY003870/unableToExtractParameter shows the val…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
Labels: 3.14

#2513 Update target containers
  .github/workflows/maven.yml
  .travis.yml
  testsuite/pom.xml
Labels: master

#2512 [RESTEASY-2627] Chain thenCompose properly
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedAsyncOutputStream.java
Labels: master

#2510 [RESTEASY-2689] Fix SseEventOutputImpl wrong CompletionStage composition sequence
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSEResource.java
Labels: master

#2518 [RESTEASY-2592][RESTEASY-2678] backport to 3.x
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForForwardCompatibility.java
  testsuite/integration-tests-spring/deployment/src/test/java/org/jboss/resteasy/test/spring/deployment/TypeMappingDependenciesInDeploymentTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/TypeMappingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchContextualDataTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsynchCounterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/validation/ValidationWithCDITest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/AbortMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/FilteredCookieTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipSizeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/interceptors/GzipTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/SigningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/FormUrlEncodedCharsetTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/file/TempFileDeletionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/html/HeadersInViewResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/Jackson2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/JacksonJsonViewTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterSuperClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptorMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithInterceptrTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithSerlvetFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletConditionalFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jackson2/jsonfilter/JsonFilterWithServletMultipleFiltersTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultCharsetTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/DefaultMediaTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/MultipleEndpointsWarningTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ResourceInfoInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/UriInfoTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/CookieInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/TrailingSlashTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/NotFoundErrorMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/request/PreconditionRfc7232Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/HeadContentLengthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/cdi/ApplicationScopeValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessing2Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/xxe/SecureProcessingTest.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/client/ResponseBuilderImplTest.java
Labels: 3.14

#2520 RESTEASY-2678
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProviderPriorityTest.java
Labels: 3.14

#2527 [RESTEASY-2689]:Add a test case
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/sse/bigmsg.json
Labels: master

#2532 [RESTEASY-2695] Unexpected/invalid sse event when mediaType is defined
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: 4.5

#2536 [RESTEASY-2699]:Sse test case cleanup
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/GreenHouse.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseCORSFilterTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseEventSinkTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseFilterApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
  testsuite/integration-tests/src/test/resources/org/jboss/resteasy/test/providers/sse/index.html
Labels: master

#2539 [WFLY-13790] get rid of jsonb object singleton, letting any deploymen…
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
Labels: master

#2542 [WFLY-13790] get rid of jsonb object singleton, letting any deploymen…
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
Labels: 3.13

#2547 [RESTEASY-2711] Replace deprecated Infinispan code
  resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
Labels: master

#2548 [RESTEASY-2711] Replace deprecated Infinispan code
  resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
Labels: 3.13

#2549 [RESTEASY-2711] Replace deprecated Infinispan code
  resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
Labels: 3.14

#2550 [RESTEASY-2712] Upgrade Infinispan to 11.0.3.Final
  resteasy-dependencies-bom/pom.xml
Labels: master

#2551 Upgrades 29 9 20
  resteasy-dependencies-bom/pom.xml
Labels: master

#2552 Upgrades29 9 20 3.13
  resteasy-dependencies-bom/pom.xml
Labels: 3.13
