Repository resteasy/resteasy, pull requests merged in 2020-03, with the labels that each got.

#2311 [RESTEASY-2510] Split RESTUtils to links provider and injector
  resteasy-links/src/main/java/org/jboss/resteasy/links/ClassLinksProvider.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/LinkResource.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/ObjectLinksProvider.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/RESTServiceDiscovery.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/AbstractLinksProvider.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/JsonLinkDecorator.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/LinkDecorator.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/LinksInjector.java
  resteasy-links/src/main/java/org/jboss/resteasy/links/impl/RESTUtils.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/impl/TestLinksInjector.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/ClassLinksProviderService.java
  resteasy-links/src/test/java/org/jboss/resteasy/links/test/TestClassLinksProvider.java
Labels: master

#2314 RESTEASY-2445 getlink(rel) does not work with things like github api pagination due to not splitting headers correctly
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/AbstractBuiltResponse.java
Labels: master

#2318 CDI BeanManager fix for Quarkus
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientExtension.java
Labels: master

#2320 RESTEASY-2519
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
Labels: master

#2324 [RESTEASY-2503] Throw ViolationException for EJBs with just parameter
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java
Labels: 3.12

#2323 [RESTESAY-2523] Upgrade snakeyaml to 1.26
  resteasy-dependencies-bom/pom.xml
Labels: 3.12

#2326 [RESTEASY-2522] Catch ConstraintViolationException in
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ConstraintViolationExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionDTO.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ConstraintViolationExceptionResourceImpl.java
Labels: 3.6.1.SPx

#2327 [RESTEASY-2503] Throw ViolationException for EJBs with just parameter violations
  providers/resteasy-validator-provider-11/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java
Labels: 3.6.1.SPx

#2328 [3.11] [RESTEASY-2503] Throw ViolationException for EJBs with just parameter violations.
  providers/resteasy-validator-provider/src/main/java/org/jboss/resteasy/plugins/validation/GeneralValidatorImpl.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyAbstractDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyDataObject.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyResourceIntf.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlySingletonResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatefulResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyStatelessResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/resource/EJBParameterViolationsOnlyTestApplication.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/providers/validation/NoFieldValidationEJBTest.java
Labels: 3.11

#2337 [RESTEASY-2535] Upgrade Jackson2 to 2.10.3
  resteasy-dependencies-bom/pom.xml
Labels: master
