Repository resteasy/resteasy, pull requests merged in 2020-05, with the labels that each got.

#2377 [RESTEASY-2550] Skip null parameters being processed by ParamConverte…
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ProxyInvocationHandler.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/PathParamProcessor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloClient.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
Labels: master

#2379 [RESTEASY-2550] Skip null parameters being processed by ParamConverte…
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/ProxyInvocationHandler.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/i18n/Messages.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/webtarget/PathParamProcessor.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloClient.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/HelloResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
Labels: 3.12

#2373 [RESTEASY-2542] Restore tests
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSETest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#2371 [RESTEASY-2239] updated mime4j to version 0.8.2
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  resteasy-dependencies-bom/pom.xml
Labels: master

#2363 [RESTEASY-2548] add new provider with higher priority than JaxrsFormP…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/JaxrsServerFormUrlEncodedProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/ResteasyUseContainerFormParamsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/resource/ResteasyUseContainerFormParamsFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/resource/ResteasyUseContainerFormParamsResource.java
Labels: master

#2384 [RESTEASY-2560] set scope for must junit dependencies to test
  providers/jaxb/pom.xml
  providers/resteasy-atom/pom.xml
  providers/resteasy-html/pom.xml
  resteasy-cdi/pom.xml
  resteasy-client-api/pom.xml
  resteasy-client-jetty/pom.xml
  resteasy-client-microprofile/pom.xml
  resteasy-client-vertx/pom.xml
  resteasy-client/pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core/pom.xml
  resteasy-guice/pom.xml
  resteasy-jsapi/pom.xml
  resteasy-links/pom.xml
  resteasy-servlet-initializer/pom.xml
  resteasy-stats/pom.xml
  security/jose-jwt/pom.xml
  server-adapters/resteasy-jdk-http/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  server-adapters/resteasy-netty4/pom.xml
  server-adapters/resteasy-undertow-spring/pom.xml
  server-adapters/resteasy-undertow/pom.xml
  server-adapters/resteasy-vertx/pom.xml
  testsuite/integration-tests-spring-web/pom.xml
  testsuite/integration-tests-spring/pom.xml
Labels: master

#2393 [RESTEASY-2472] Prevent timeout handler from running if request doesn…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java
Labels: 3.12

#2394 [RESTEASY-2391] changed code to use getMethod()
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
Labels: 3.12

#2372 [RESTEASY-2472]:@Suspended AsyncResponse timeout still runs, even if …
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java
Labels: master

#2396 [RESTEASY-2563: SseBroadcasterImpl.close() puts notifyOnCloseListener…
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseBroadcasterImpl.java
Labels: master

#2389 [RESTEASY-2576] added client modules
  resteasy-bom/pom.xml
Labels: master

#2390 CompletionStageResponseTest intermittent failures
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncRequestFilter.java
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/async/AsyncResponseFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncRequestFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncResponseFilter.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/CallbackSecondSettingCompletionCallback.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/CallbackSettingCompletionCallback.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/CompletionStageResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseNoStreamTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/PublisherResponseTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/SingleProvider.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/AsyncResponseCallback.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/CompletionStageResponseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseNoStreamResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/PublisherResponseResource.java
Labels: Do Not Merge, master

#2398 [RESTEASY-2580] Remove duplicated dependencies in POMs
  resteasy-client/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: 3.12

#2397 [RESTEASY-2580] Remove duplicated dependencies in POMs
  resteasy-client/pom.xml
  resteasy-dependencies-bom/pom.xml
Labels: 3.11

#2381 [RESTEASY-2571] Avoid a NullPointerException of the MediaType associa…
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
Labels: master

#2375 [RESTEASY-2569] RestClient does not propogate incoming headers
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeadersRequestFilter.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/utils/ClientRequestContextUtils.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ClientHeadersFactoryCDITest.java
Labels: master

#2401 [RESTEASY-2582] Add logs to the test
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/resource/AsyncResponseCallback.java
Labels: master

#2403 [RESTEASY-2569] backporting fix
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/header/ClientHeadersRequestFilter.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/utils/ClientRequestContextUtils.java
  resteasy-client-microprofile/src/test/java/org/jboss/resteasy/microprofile/client/ClientHeadersFactoryCDITest.java
Labels: 3.12

#2405 [RESTEASY-1203] Fix validation for JNDI resources.
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ManagedBeanValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ManagedBeanValidationApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ManagedBeanValidationResource.java
Labels: 3.12

#2406 [RESTEASY-1203] Fix validation for JNDI resources.
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ManagedBeanValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ManagedBeanValidationApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/resource/ManagedBeanValidationResource.java
Labels: master

#2407 [RESTEASY-2581] Add profile to enable testing using Wildfly "standalone-microprofile.xml" configuration file
  .travis.yml
  testsuite/README.MD
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingBecauseOfSmallRyeMicroprofileOpenApi11.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingWithStandaloneMicroprofileConfiguration.java
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/AsynchronousCdiTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EJBTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EjbExceptionUnwrapTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/OutOfBandTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/SingletonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationEJBProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionJpaEnumTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/TimerInterceptorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ParameterListTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/GenericProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyWithGenericReturnTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/AnnotationInheritanceGenericsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ParameterSubResTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/FormParamTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamCustomClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDateNoProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDateProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/LocatorSubResourceReturningThisTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
Labels: 3.12

#2408 [RESTEASY-2560] Updated junit dependencies to test scope.
  resteasy-jaxrs/pom.xml
  resteasy-jsapi/pom.xml
  resteasy-links/pom.xml
  server-adapters/resteasy-jdk-http/pom.xml
  server-adapters/resteasy-netty/pom.xml
  server-adapters/resteasy-netty4/pom.xml
  server-adapters/resteasy-vertx/pom.xml
Labels: 3.12

#2404 [RESTEASY-2542]:Fix Sse test
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#2361 [RESTEASY-2017]:Fix SSE doesn't work with inherited annotations
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPI.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPIImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPITest.java
Labels: master

#2409 Updated links to the new project site
  README.md
Labels: master

#2411 [RESTEASY-2588] Upgrade jackson to 2.10.4
  resteasy-dependencies-bom/pom.xml
Labels: master

#2410 [RESTEASY-2587] Update classmate to 1.5.1
  resteasy-dependencies-bom/pom.xml
Labels: master

#2412 Sync 15 5 20
  README.md
  resteasy-dependencies-bom/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPI.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPIImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseAPITest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: 3.12

#2416 [RESTEASY-2576] Added modules to resteasy-bom/pom.xml
  resteasy-bom/pom.xml
Labels: 3.12

#2417 [RESTEASY-2576] Added modules to resteasy-bom/pom.xml
  resteasy-bom/pom.xml
Labels: master

#2413 [RESTEASY-2590] Update dependencies to match WildFly 20
  resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheInterceptor.java
  resteasy-cache/resteasy-cache-core/src/test/resources/infinispan.xml
  resteasy-dependencies-bom/pom.xml
  security-legacy/keystone/keystone-core/src/main/java/org/jboss/resteasy/keystone/model/Access.java
  security-legacy/keystone/keystone-core/src/main/java/org/jboss/resteasy/keystone/model/Role.java
  security-legacy/keystone/keystone-core/src/main/java/org/jboss/resteasy/keystone/model/StoredProject.java
  security-legacy/keystone/keystone-core/src/main/java/org/jboss/resteasy/keystone/model/StoredUser.java
  security-legacy/keystone/keystone-core/src/test/resources/cache.xml
Labels: 3.12

#2399 [RESTEASY-2581] Add profile to enable testing using Wildfly "standalone-microprofile.xml" configuration file
  .travis.yml
  testsuite/README.MD
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingBecauseOfSmallRyeMicroprofileOpenApi11.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/ExpectedFailingWithStandaloneMicroprofileConfiguration.java
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/AsynchronousCdiTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EJBTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EjbExceptionUnwrapTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/OutOfBandTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/SingletonTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationEJBProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/ejb/EJBCDIValidationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionJpaEnumTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/interceptors/TimerInterceptorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ParameterListTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/GenericProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/proxy/ProxyWithGenericReturnTypeTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/AnnotationInheritanceGenericsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/form/Resteasy1405Test.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseBroadcastTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/basic/ParameterSubResTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/FormParamTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamCustomClassTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDateNoProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/param/MultiValuedParamDateProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/path/LocatorSubResourceReturningThisTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
  testsuite/pom.xml
Labels: 3.11

#2426 How to run a single microprofile-ck test
  testsuite/README.MD
Labels: master

#2332 RESTEASY-2524
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
Labels: master
