Repository resteasy/resteasy, pull requests merged in 2020-10, with the labels that each got.

#2526 (3.13) Adding support for running test suite against bootable JAR
  pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/README.MD
  testsuite/arquillian-utils/pom.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/category/NotForBootableJar.java
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cache/ServerCacheInterceptorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/CDIResourceTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/InjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/MDBInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/injection/ReverseInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/ClientBuilderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/basic/DuplicateDeploymentTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/logging/DebugLoggingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/core/spi/ResourceClassProcessorErrorTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/crypto/CryptoTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/DuplicateProviderRegistrationTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/custom/MissingProducerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/jsonb/basic/JsonBindingDebugLoggingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/EncodingMimeMultipartFormProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/MimeMultipartProviderTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/response/DuplicitePathTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/warning/SubResourceWarningTest.java
  testsuite/integration-tests/src/test/resources/arquillian-bootable.xml
  testsuite/pom.xml
Labels: 3.13

#2571 [RESTEASY-2735]:Upgrade projectreactor to 3.3.10.RELEASE
  resteasy-dependencies-bom/pom.xml
  resteasy-reactor/pom.xml
Labels: master

#2576 [RESTEASY-2741]:Upgrade rxjava2 and other components
  resteasy-dependencies-bom/pom.xml
Labels: master

#2568 RESTEASY-2734 The current WADL GRAMMAR generation logic incorrectly c…
  resteasy-wadl-undertow-connector/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLUndertowContainerTest.java
  resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlDefaultResource.java
  resteasy-wadl/src/main/java/org/jboss/resteasy/wadl/ResteasyWadlWriter.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/MyWadlResource.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/TestWadlFunctions.java
  resteasy-wadl/src/test/java/org/jboss/resteasy/test/nextgen/wadl/WADLNettyContainerTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/wadl/WadlTestApplication.java
Labels: master

#2579 RESTEASY-2739 - Update WADL section document
  docbook/reference/en/en-US/modules/WADL.xml
Labels: master

#2581 [WFLY-13790] get rid of jsonb object singleton, letting any deploymen…
  providers/json-binding/src/main/java/org/jboss/resteasy/plugins/providers/jsonb/AbstractJsonBindingProvider.java
Labels: 3.11

#2583 Fix bootable jar profile for branch 3.11
  testsuite/pom.xml
Labels: 3.11
