Repository resteasy/resteasy, pull requests merged in 2020-04, with the labels that each got.

#2341 [RESTEASY-2541] Fix RestClientListeners
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/RestClientListeners.java
Labels: master

#2343 [RESTEASY-2542] Excluding tests
  server-adapters/resteasy-vertx/src/test/java/org/jboss/resteasy/test/asyncio/SSETest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseTest.java
Labels: master

#2349 RESTEASY-2554 Update section "Upgrading RESTEasy within WildFly"
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
Labels: master

#2353 [JBEAP-18700] Improper validation of response header in MediaTypeHead…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mediatype/MediaTypeHeaderTest.java
Labels: 3.6.1.SPx

#2334 [RESTEASY-2385] Added support for embedded MultipartOutput types. Add…
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartInputImpl.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/MultipartRelatedInputImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/ComplexMultipartOutputTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/SoupMultipartMsgTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/ComplexMultipartOutputResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/Soup.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/multipart/resource/SoupVendorResource.java
Labels: master

#2357 [RESTEASY-2559] Improper validation of response header in MediaTypeHe…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/plugins/delegates/MediaTypeHeaderDelegate.java
  testsuite/unit-tests/src/test/java/org/jboss/resteasy/test/mediatype/MediaTypeHeaderTest.java
Labels: 3.11

#2365 [RESTEASY-2562] Incorrect status code when WebApplicationException is…
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/ResourceConstructorParamsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorCookieParamWAEResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/ConstructorQueryParamWAEResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/Item2.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/constructor/resource/Item2ParamConverterProvider.java
Labels: master

#2292 [RESTEASY-2495] ParamConverter not being applied to HeaderParam
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/proxy/processors/invocation/HeaderParamProcessor.java
Labels: master

#2254 [RESTEASY-2466] removed profile arquillian.remote
  testsuite/README.MD
  testsuite/arquillian-utils/pom.xml
Labels: master

#2335 [RESTEASY-2531] expanded and refactored chapter
  docbook/reference/en/en-US/modules/Multipart.xml
Labels: master

#2344 [RESTEASY-2544] pom updates to arquillian-util and integration-tests
  testsuite/arquillian-utils/pom.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/PortProviderUtil.java
  testsuite/integration-tests/assembly/assembly.xml
  testsuite/integration-tests/pom.xml
Labels: master

#2348 [RESTEASY-2542] ignore any IOException in SSEOutputStream.close()
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/sse/SseEventOutputImpl.java
Labels: master

#2369 Test against WildFly 19.0.0.Final instead of Beta2
  .travis.yml
  testsuite/pom.xml
Labels: master

#2370 [RESTEASY-2526] Turn the com.ibm.async.asyncutil module into private
  jboss-modules/src/main/resources/modules/com/ibm/async/asyncutil/main/module.xml
Labels: master
