Repository resteasy/resteasy, pull requests merged in 2020-08, with the labels that each got.

#2484 RESTEASY-2662 Don't create a context if it does not exist
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
Labels: master

#2485 [RESTEASY-2666] Upgrade httpclient/httpcore
  resteasy-dependencies-bom/pom.xml
Labels: master

#2483 [RESTEASY-2633] Encode code points that span multiple characters
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/util/Encode.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/RestClientProxyTest.java
Labels: 3.14

#2486 [RESTEASY-2666] Upgrade httpclient/httpcore
  resteasy-dependencies-bom/pom.xml
Labels: 3.14

#2490 RESTEASY-2674 Escape sign of quotation to see the value of parameter
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
Labels: master

#2466 Resteasy 2618 mp rest client query param style 2 nd
  resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/RestClientBuilderImpl.java
  resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/impl/MpClient.java
  resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/impl/MpClientWebTarget.java
  resteasy-client-microprofile-base/src/main/java/org/jboss/resteasy/microprofile/client/impl/MpUriBuilder.java
  resteasy-core/src/main/java/org/jboss/resteasy/specimpl/ResteasyUriBuilderImpl.java
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/QueryParamStyleMPConfigPropertyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/QueryParamStyleTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/resource/QueryParamStyleService.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/resource/QueryParamStyleServiceIntf.java
Labels: MP REST Client 2.0

#2498 [RESTEASY-2661]:MediaTypeMap shared across threads, but cache is not …
  resteasy-core/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java
Labels: master
