Repository resteasy/resteasy, pull requests merged in 2020-02, with the labels that each got.

#2283 [RESTEASY-2302] Memory usage improvements for client configuration in…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/MediaTypeMap.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/interception/JaxrsInterceptorRegistry.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
Labels: 3.11

#2285 RESTEASY-2490 Upgrade Netty to 4.1.45
  resteasy-dependencies-bom/pom.xml
Labels: master

#2279 [RESTEASY-2488] Upgrade to Infinispan 10.1.1.Final
  resteasy-cache/resteasy-cache-core/pom.xml
  resteasy-cache/resteasy-cache-core/src/main/java/org/jboss/resteasy/plugins/cache/server/ServerCacheFeature.java
  resteasy-cache/resteasy-cache-core/src/test/resources/infinispan.xml
  resteasy-dependencies-bom/pom.xml
Labels: master

#2288 RESTEASY-2493 - Update the document: 'Spring MVC section'
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
Labels: master

#2287 [RESTEASY-1986] Lower log level to DEBUG as the exception is rethrown
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
Labels: 3.6.1.SPx

#2293 [RESTEASY-2481] Upgrade to MP Config 1.4
  resteasy-dependencies-bom/pom.xml
Labels: 3.11

#2295 Resteasy 2481 1.4.0 3.x
  resteasy-dependencies-bom/pom.xml
Labels: 3.11

#2296 Resteasy 2481 1.4.0
  resteasy-dependencies-bom/pom.xml
Labels: master

#2299 [RESTEASY-2481] Update User Guide for MP REST Client
  docbook/reference/en/en-US/modules/MicroProfile_Rest_Client.xml
Labels: 3.11

#2300 Test against latest WFLY 19 (Beta2)
  .travis.yml
  testsuite/pom.xml
Labels: master

#2301 Test against latest WFLY 19 (Beta2)
  .travis.yml
  testsuite/pom.xml
Labels: 3.11

#2297 RESTEASY-2494 update resteasy-undertow-spring integration section
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
Labels: master

#2302 RESTEASY-2501 update document: resteasy-spring-rest usage example nee…
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
Labels: master

#2303 RESTEASY-2502 - revisit Spring Boot starter doc section to keep it up…
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
Labels: master

#2304 [RESTEASY-2496]:Add test case
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
Labels: master
