Repository resteasy/resteasy, pull requests merged in 2021-03, with the labels that each got.

#2681 [RESTEASY-2841] Attempt to load the API types before the implementation.
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfig.java
Labels: 3.15

#2683 [RESTEASY-2799] Check if we're not on the server side first before as…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
Labels: 3.15

#2665 [RESTEASY-2820] Clients running in a resource method throw safer WebA…
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-client-api/pom.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/ThreadLocalStack.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
Labels: 4.4

#2678 Update CorsFilter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/interceptors/CorsFilter.java
Labels: master

#2680 [RESTEASY-2826] resteasy-vertx: Response Headers with String value of same type are overwritten
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpResponse.java
Labels: master

#2668 RESTEASY-2816 - Update the RESTEasy Spring document
  docbook/pom.xml
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
  docbook/scripts/after.java
  docbook/scripts/before.java
Labels: master

#2703 [RESTEASY-2861] Upgrade jetty server to 9.4.39
  resteasy-dependencies-bom/pom.xml
Labels: master

#2704 Upgrade Vert.x to 4.0.3 and Netty to 4.1.60
  resteasy-dependencies-bom/pom.xml
Labels: master
