Repository resteasy/resteasy, pull requests merged in 2021-02, with the labels that each got.

#2661 [RESTEASY-2779] Removed redundant call in ResourceMethodRegistry.
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
Labels: master

#2660 [RESTEASY-2779] Remove redundant call in ResourceMethodRegistry.
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/ResourceMethodRegistry.java
Labels: 3.15

#2671 [RESTEASY-2825 Clients running in a resource method throw safer WebAp…
  docbook/reference/en/en-US/modules/ExceptionMappers.xml
  docbook/reference/en/en-US/modules/Installation_Configuration.xml
  resteasy-client-api/pom.xml
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyBadRequestException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyClientErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyForbiddenException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyInternalServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAcceptableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAllowedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotAuthorizedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotFoundException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyNotSupportedException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyRedirectionException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServerErrorException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyServiceUnavailableException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/ResteasyWebApplicationException.java
  resteasy-client-api/src/main/java/org/jboss/resteasy/client/exception/WebApplicationExceptionWrapper.java
  resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/DefaultResponseExceptionMapper.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/internal/ClientInvocation.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyDeployment.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/ResteasyProviderFactory.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyContext.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryDelegate.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/providerfactory/ResteasyProviderFactoryImpl.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/main/java/org/jboss/resteasy/util/ThreadLocalStack.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionMicroProfileProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionResteasyProxyTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/ClientWebApplicationExceptionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionMicroProfileProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionProxyResourceInterface.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyApplication.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/client/exception/resource/ClientWebApplicationExceptionResteasyProxyResource.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/ClosedResponseHandlingTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/exception/resource/ClosedResponseHandlingResource.java
Labels: 4.5

#2667 [RESTEASY-2822]:Conditionally add AcceptHeaderByFileSuffixFilter
  resteasy-core/src/main/java/org/jboss/resteasy/core/AcceptHeaderByFileSuffixFilter.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResteasyDeploymentImpl.java
Labels: master

#2675 [RESTEASY-2805] Remove dependency on MicroProfile Config.
  resteasy-jaxrs/pom.xml
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfig.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/microprofile/config/ResteasyConfigProvider.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/config/resource/ResteasyConfigResource.java
Labels: 3.15

#2676 [RESTEASY-2830] Update dependencies
  resteasy-dependencies-bom/pom.xml
Labels: 3.15
