Repository resteasy/resteasy, pull requests merged in 2021-09, with the labels that each got.

#2806 Fixing the ResteasyViolationException#toString concurrency
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
Labels: 3.9

#2817 Fixing the ResteasyViolationException#toString concurrency
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
Labels: 3.11

#2816 Fixing the ResteasyViolationException#toString concurrency
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ResteasyViolationException.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/api/validation/ViolationReport.java
Labels: 3.15

#2866 [RESTEASY-2970] SsePublisherClientTest fails with bootable-jar
  testsuite/integration-tests/pom.xml
Labels: 3.15
