Repository resteasy/resteasy, pull requests merged in 2021-07, with the labels that each got.

#2860 Resolve version convergence issue with jboss-threads dependency
  resteasy-dependencies-bom/pom.xml
Labels: 4.6

#2862 Resolve version convergence issue with jboss-threads dependency
  resteasy-dependencies-bom/pom.xml
Labels: main

#2776 [RESTEASY-2880] Config options for in-memory limit
  providers/multipart/pom.xml
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/HeaderFlushedOutputStream.java
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
  providers/multipart/src/test/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaroundTest.java
  resteasy-client/src/main/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43Engine.java
  resteasy-client/src/test/java/org/jboss/resteasy/client/jaxrs/engines/ManualClosingApacheHttpClient43EngineTest.java
Labels: main

#2867 [RESTEASY-2971] FollowRedirectsTest should be annotated with MicroProfileDependent category
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/microprofile/restclient/FollowRedirectsTest.java
Labels: 3.15

#2864 [RESTEASY-2968] Fix rxjava2 related testing for bootable jar
  testsuite/integration-tests/pom.xml
Labels: 3.15
