Repository resteasy/resteasy, pull requests merged in 2021-04, with the labels that each got.

#2709 [RESTEASY-2861] Upgrade jetty server to 9.4.39
  resteasy-dependencies-bom/pom.xml
Labels: 4.5

#2712 [RESTEASY-2864] Fixed proxy call in Chapter 52 of User Guide.
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
Labels: master

#2713 [RESTEASY-2864] Fixed code in Chapter 52 of User Guide.
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
Labels: 4.6

#2714 [RESTEASY-2864] Fixed code in Chapter 52 of User Guide.
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
Labels: 4.5

#2715 [RESTEASY-2864] Fixed code in Chapter 52 of User Guide.
  docbook/reference/en/en-US/modules/RESTEasy_Client_Framework.xml
Labels: 3.15

#2718 [RESTEASY-2857] re-scoped resteasy-client dependency
  profiling-tests/pom.xml
  providers/multipart/pom.xml
Labels: 4.5

#2719 [RESTEASY-2857] re-scoped resteasy-client dependency
  profiling-tests/pom.xml
  providers/multipart/pom.xml
Labels: 4.6

#2711 [RESTEASY-2854] corrected when onError is called
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java
Labels: main

#2729 [RESTEASY-2854] corrected when onError is called
  resteasy-client/src/main/java/org/jboss/resteasy/plugins/providers/sse/client/SseEventSourceImpl.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/SseReconnectTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/providers/sse/resource/SseReconnectResource.java
Labels: 4.5

#2682 [RESTEASY-2842] DoPriv for file access in Mime4JWorkaround
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
Labels: main

#2732 [RESTEASY-2842] DoPriv for file access in Mime4JWorkaround
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
Labels: 4.6

#2733 [RESTEASY-2842] DoPriv for file access in Mime4JWorkaround
  providers/multipart/src/main/java/org/jboss/resteasy/plugins/providers/multipart/Mime4JWorkaround.java
Labels: 4.5

#2738 [RESTEASY-2865] setTimeout(..) in TimeoutHandler
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java
Labels: 4.6

#2737 [RESTEASY-2865] setTimeout(..) in TimeoutHandler
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java
Labels: 4.5

#2716 [RESTEASY-2865] setTimeout(..) in TimeoutHandler
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/Servlet3AsyncHttpRequest.java
  server-adapters/resteasy-netty4/src/main/java/org/jboss/resteasy/plugins/server/netty/NettyHttpRequest.java
  server-adapters/resteasy-vertx/src/main/java/org/jboss/resteasy/plugins/server/vertx/VertxHttpRequest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/AsyncTimeoutTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/asynch/resource/AsyncTimeoutResource.java
Labels: main

#2739 RESTEASY-2816 4.6
  docbook/pom.xml
  docbook/reference/en/en-US/modules/RESTEasy_Spring_Integration.xml
  docbook/scripts/after.java
  docbook/scripts/before.java
Labels: 4.6

#2736 [RESTEASY-2868] Use a handler to pause the client response while
  resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
Labels: main

#2745 Only set the status of response with @ResponseStatus if it's not alre…
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusContainerResponseFilter.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusFeature.java
Labels: 4.5

#2744 Only set the status of response with @ResponseStatus if it's not alre…
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusContainerResponseFilter.java
  resteasy-spring-web/src/main/java/org/jboss/resteasy/spring/web/ResponseStatusFeature.java
Labels: 4.6

#2741 [RESTEASY-2843] Do not add the target type to the thrown exception. I…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
Labels: main

#2743 [RESTEASY-2868] Use a handler to pause the client response while the …
  resteasy-client-vertx/src/main/java/org/jboss/resteasy/client/jaxrs/engines/vertx/VertxClientHttpEngine.java
Labels: 4.6

#2746 [RESTEASY-2843] Do not add the target type to the thrown exception. I…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
Labels: 4.5

#2748 [RESTEASY-2843] Do not add the target type to the thrown exception. I…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
Labels: 3.15

#2749 [RESTEASY-2843] Do not add the target type to the thrown exception. I…
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-jaxrs/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
Labels: 3.11

#2747 [RESTEASY-2843] Do not add the target type to the thrown exception. I…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/LogMessages.java
  resteasy-core-spi/src/main/java/org/jboss/resteasy/resteasy_jaxrs/i18n/Messages.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/StringParameterInjector.java
Labels: 4.6

#2750 [RESTEASY-2869]:Cache the hasDecorator result in Jackson2Provider
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java
Labels: 4.6

#2751 [RESTEASY-1721] ResourceMethodInvoker checks if @Context HttpServletR…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/HttpServletResponseContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/resource/HttpServletResponseContextResource.java
Labels: main

#2752 [RESTEASY-1721] ResourceMethodInvoker checks if @Context HttpServletR…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/HttpServletResponseContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/resource/HttpServletResponseContextResource.java
Labels: 4.5

#2753 [RESTEASY-1721] ResourceMethodInvoker checks if @Context HttpServletR…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/HttpServletResponseContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/context/resource/HttpServletResponseContextResource.java
Labels: 4.6

#2759 [RESTEASY-1721] Eliminate ContextParameterInjector's dependence on se…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextServletOutputStream.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
Labels: 4.5
