Repository resteasy/resteasy, pull requests merged in 2021-05, with the labels that each got.

#2764 [RESTEASY-2849]:JsonPatch/JsonMergePatch implementation with JSONP
  providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/PatchMethodFilter.java
  providers/json-p-ee7/src/main/java/org/jboss/resteasy/plugins/providers/jsonp/JsonpPatchMethodFilter.java
  providers/json-p-ee7/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/providers/AbstractPatchMethodFilter.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/resource/patch/StudentPatchTest.java
Labels: main

#2787 [RESTEASY-1721] Eliminate ContextParameterInjector's dependence on se…
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextServletOutputStream.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
Labels: main

#2768 [RESTEASY-2876] Move the Arquillian BOM import out of the dependency …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-736-jetty/pom.xml
  arquillian/pom.xml
  pom.xml
  resteasy-dependencies-bom/pom.xml
  server-adapters/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/pom.xml
Labels: 3.11

#2771 [RESTEASY-2876] Move the Arquillian BOM import out of the dependency …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-736-jetty/pom.xml
  arquillian/pom.xml
  pom.xml
  resteasy-dependencies-bom/pom.xml
  server-adapters/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/pom.xml
Labels: 3.15

#2772 [RESTEASY-2876] Move the Arquillian BOM import out of the dependency …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  arquillian/RESTEASY-736-jetty/pom.xml
  arquillian/pom.xml
  pom.xml
  resteasy-dependencies-bom/pom.xml
  server-adapters/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  testsuite/arquillian-utils/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/pom.xml
Labels: main

#2792 [RESTEASY-2866] Make proxy interface check configurable
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextServletOutputStream.java
  resteasy-core/src/main/java/org/jboss/resteasy/core/ResourceMethodInvoker.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/test/java/org/jboss/resteasy/core/ContextParameterInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/contextProxyInterfaces/ContextProxyInterfacesTest.java
Labels: 4.6

#2777 [RESTEASY-2866] Make proxy interface check configurable
  resteasy-core/src/main/java/org/jboss/resteasy/core/ContextParameterInjector.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ConfigurationBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ResteasyContextParameters.java
  resteasy-core/src/test/java/org/jboss/resteasy/core/ContextParameterInjectionTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/contextProxyInterfaces/ContextProxyInterfacesTest.java
Labels: main

#2789 [RESTEASY-2888] Change sub-modules to use their direct parent module …
  arquillian/RESTEASY-1056-jetty-bv11/pom.xml
  arquillian/RESTEASY-1630-jetty-resteasy-servlet-initializer/pom.xml
  arquillian/RESTEASY-736-jetty/pom.xml
  arquillian/pom.xml
  docbook/pom.xml
  pom.xml
  profiling-tests/pom.xml
  providers/fastinfoset/pom.xml
  providers/jackson2/pom.xml
  providers/jaxb/pom.xml
  providers/json-binding/pom.xml
  providers/json-p-ee7/pom.xml
  providers/multipart/pom.xml
  providers/pom.xml
  providers/resteasy-atom/pom.xml
  providers/resteasy-html/pom.xml
  providers/resteasy-validator-provider/pom.xml
  resteasy-bom/pom.xml
  resteasy-cache/resteasy-cache-core/pom.xml
  resteasy-cdi/pom.xml
  resteasy-client-api/pom.xml
  resteasy-client-jetty/pom.xml
  resteasy-client-microprofile/pom.xml
  resteasy-client-reactor-netty/pom.xml
  resteasy-client-vertx/pom.xml
  resteasy-client/pom.xml
  resteasy-core-spi/pom.xml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  resteasy-guice/pom.xml
  resteasy-jsapi/pom.xml
  resteasy-links/pom.xml
  resteasy-reactive-context/pom.xml
  resteasy-reactor/pom.xml
  resteasy-rxjava2/pom.xml
  resteasy-servlet-initializer/pom.xml
  resteasy-spring/pom.xml
  resteasy-stats/pom.xml
  resteasy-wadl-undertow-connector/pom.xml
  resteasy-wadl/pom.xml
  security/jose-jwt/pom.xml
  security/pom.xml
  security/resteasy-crypto/pom.xml
  server-adapters/resteasy-jdk-http/pom.xml
  server-adapters/resteasy-netty4-cdi/pom.xml
  server-adapters/resteasy-netty4/pom.xml
  server-adapters/resteasy-reactor-netty/pom.xml
  server-adapters/resteasy-undertow-spring/pom.xml
  server-adapters/resteasy-undertow/pom.xml
  server-adapters/resteasy-vertx/pom.xml
  testsuite/arquillian-utils/pom.xml
  testsuite/integration-tests-embedded/pom.xml
  testsuite/integration-tests-spring-web/pom.xml
  testsuite/integration-tests-spring/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/microprofile-tck/pom.xml
  testsuite/pom.xml
  testsuite/unit-tests/pom.xml
Labels: main

#2790 [RESTEASY-2892] Make sure the ResteasyConfiguration also checks the S…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/DefaultConfiguration.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/FilterBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletBootstrap.java
Labels: 4.6

#2799 [RESTEASY-2892] Make sure the ResteasyConfiguration also checks the S…
  resteasy-core-spi/src/main/java/org/jboss/resteasy/spi/config/DefaultConfiguration.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/FilterBootstrap.java
  resteasy-core/src/main/java/org/jboss/resteasy/plugins/server/servlet/ServletBootstrap.java
Labels: main

#2800 Component upgrades for 4.6
  .github/workflows/maven.yml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/pom.xml
Labels: 4.6

#2796 [RESTEASY-2886] RESTEasy Java 16 Fixes
  .github/workflows/maven.yml
  pom.xml
  resteasy-core/pom.xml
  resteasy-dependencies-bom/pom.xml
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/setup/AbstractUsersRolesSecurityDomainSetup.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtil.java
  testsuite/arquillian-utils/src/main/java/org/jboss/resteasy/utils/TestUtilSpring.java
  testsuite/integration-tests-spring-web/pom.xml
  testsuite/integration-tests-spring/deployment/pom.xml
  testsuite/integration-tests-spring/inmodule/pom.xml
  testsuite/integration-tests-spring/inmodule/src/test/java/org/jboss/resteasy/test/spring/inmodule/SpringMvcHttpResponseCodesTest.java
  testsuite/integration-tests-spring/pom.xml
  testsuite/integration-tests/pom.xml
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/cdi/basic/EJBTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/BasicAuthTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/CustomForbiddenMessageTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/SecurityContextTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/security/TwoSecurityDomainsTest.java
  testsuite/integration-tests/src/test/java/org/jboss/resteasy/test/validation/ejb/EJBParameterViolationsOnlyTest.java
  testsuite/microprofile-tck/pom.xml
  testsuite/pom.xml
Labels: main
